### ISSUE TITLE
`arm64` Releases

### ISSUE THREAD

**Issue by fjij** [lanylow/rbxfpsunlocker-osx#1]
Not sure whether you're running on Intel or Apple Silicon but I'm running on Apple Silicon and can build native `arm64` releases if you need it :D

**Comment by lanylow** [comment]
This was tested only on an intel mac. Does Roblox even have a native arm64 version or is it emulated?

**Comment by fjij** [comment]
It's emulated

**Comment by fjij** [comment]
Well I'll let you know if there's any issues once you make a release 👍
