### ISSUE TITLE
Rosetta not used on M1

### ISSUE THREAD

**Issue by mist-l** [lanylow/rbxfpsunlocker-osx#10]
Since it's a shell script, it doesn't have to be recompiled. It works the same

**Comment by lanylow** [comment]
What's the issue?

**Comment by mist-l** [comment]
No issue, you should just remove “works via Rosetta 2” in the readme since that’s not what it’s doing

**Comment by lanylow** [comment]
What do you mean? It is a x86 executable, it has to run under Rosetta 2.

**Comment by mist-l** [comment]
I guess I'm mistaken then. Sorry, not really my field of expertise
