### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by wiz23424** [lanylow/rbxfpsunlocker-osx#101]
Whenever I try to use the fps unlocking command, it shows "command not found", I've followed all the steps correctly but there seems to be no change (btw roblox is open in this screenshot and the game is fully loaded).

![Screenshot 2022-11-04 at 7 05 56 PM](https://user-images.githubusercontent.com/117457899/199985699-93049d99-b853-4af9-9f21-0714972d8e76.png)

**Comment by 1Castiel** [comment]
yeah same thing happening to me, I'd restart my mac, redownload the file after fully deleting and retrying over and over. Same thing pops up, "no command found"

**Comment by lanylow** [comment]
Remove the dot after sudo.
