### ISSUE TITLE
Issue with New UI

### ISSUE THREAD

**Issue by goon19** [lanylow/rbxfpsunlocker-osx#102]
The application must be launched while Roblox Player is not open,  Not doing so will make the UI disappear and won't change your fps, This also happens when used more than 4-5 times or after 2-4 days of normal use.

**Comment by goon19** [comment]
[macOS FPS Unlocker v1.2.0](https://github.com/lanylow/rbxfpsunlocker-osx/releases/tag/v1.2.0) is the version.

**Comment by SeizureSaladd** [comment]
huh i'll check this out later
