### ISSUE TITLE
Issue with detecting roblox

### ISSUE THREAD

**Issue by Matt-design542** [lanylow/rbxfpsunlocker-osx#104]
The rbxfpsunlocker cannot detect roblox even when its open. Even when resetting my computer and doing other checks this is not a problem with just my computer. I have seen others with the same issue which just started today. This may be only for few users as it may be because of the type of mac or everyone but I doubt it is for few people as it was working before.

**Comment by grrrrrrbear** [comment]
For me it says it unlock the fps in terminal but in reality it doesnt work

**Comment by mr-kiru** [comment]
for me everything is perfect.
but i dont have 120hz monitor sadly

**Comment by lanylow** [comment]
Please refer to instructions from the latest release.
