### ISSUE TITLE
Issue with running the new software

### ISSUE THREAD

**Issue by russiakick3000** [lanylow/rbxfpsunlocker-osx#105]
Tried running it as it said and still got the same issues, for some reason when I add the -r at the end it just doesn't say anything after the input and doesn't unlock the fps. I have tried a lot to go past this issue like running it as a shortcut and so on but same issue every time. Also when I join with the GUI enabled it just says the same thing from before.

**Comment by creamywastaken** [comment]
same

**Comment by lanylow** [comment]
You are supposed to run it with `-r` when Roblox is closed, then open Roblox, and run it without the `-r`.

**Comment by russiakick3000** [comment]
> You are supposed to run it with `-r` when Roblox is closed, then open Roblox, and run it without the `-r`.

Tried it before but haven't tried it after. So I use the first command line with the -r before I run it then I run it again while roblox is open without the r?

**Comment by creamywastaken** [comment]
thanks, it worked

**Comment by lanylow** [comment]
> > You are supposed to run it with `-r` when Roblox is closed, then open Roblox, and run it without the `-r`.
> 
> Tried it before but haven't tried it after. So I use the first command line with the -r before I run it then I run it again while roblox is open without the r?

Correct.

**Comment by russiakick3000** [comment]
> > > You are supposed to run it with `-r` when Roblox is closed, then open Roblox, and run it without the `-r`.
> > 
> > 
> > Tried it before but haven't tried it after. So I use the first command line with the -r before I run it then I run it again while roblox is open without the r?
> 
> Correct.

tried it ended up getting this "exception: base_process constructor failed"

**Comment by James22rx** [comment]
is there a way to fix the fps unlocker while using macOS ventura?

**Comment by James22rx** [comment]
> thanks, it worked

hi are you on macOS ventura?
and which version of the unlocker do u use?

**Comment by lanylow** [comment]
> is there a way to fix the fps unlocker while using macOS ventura?

Read additional information on the latest release.

**Comment by lanylow** [comment]
> > > > You are supposed to run it with `-r` when Roblox is closed, then open Roblox, and run it without the `-r`.
> > > 
> > > 
> > > Tried it before but haven't tried it after. So I use the first command line with the -r before I run it then I run it again while roblox is open without the r?
> > 
> > 
> > Correct.
> 
> tried it ended up getting this "exception: base_process constructor failed"

This means you didn't run it correctly. First, close Roblox and run `sudo ./rbxfpsunlocker_osx 0 -r`, then launch Roblox and run `sudo ./rbxfpsunlocker_osx 0`. Of course you can edit the file path to your needs.

**Comment by russiakick3000** [comment]
> 

Even still its giving me the same errors, might be not updating my software to Ventura. I'll try a software update and see how that goes. But thanks for the help I appreciate it a lot.
