### ISSUE TITLE
disabling g sync on ventura

### ISSUE THREAD

**Issue by creamywastaken** [lanylow/rbxfpsunlocker-osx#106]
does anybody how to disable g sync on macos ventura? im on a macbook with promotion so i only get 120 fps, ive tried quartz debug but it didnt seem to work, its probably impossible but i just want to know
<img width="1512" alt="Screenshot 2022-11-05 at 11 02 19 pm" src="https://user-images.githubusercontent.com/117515284/200118937-6035b5b5-57c0-4744-9d00-55ab5aea704c.png">

**Comment by grrrrrrbear** [comment]
i think it is on google 

https://www.youtube.com/results?search_query=mac+vsync+roblox

**Comment by James22rx** [comment]
excuse me creamy
are you on macos ventura?

**Comment by James22rx** [comment]
how do i unlock my frames

**Comment by James22rx** [comment]
can you tell me what version and things i need to do

**Comment by lanylow** [comment]
Quartz Debug doesn't seem to work on ventura and I don't know any other way of disabling it.
