### ISSUE TITLE
It says it works but it doesnt

### ISSUE THREAD

**Issue by grrrrrrbear** [lanylow/rbxfpsunlocker-osx#107]
![Skärmavbild 2022-11-05 kl  13 21 03](https://user-images.githubusercontent.com/87470326/200119608-a057c586-45b9-468f-a369-19d335854beb.png)

it doesnt work for. it says it works but it doesnt unlock it i tried in both fullscreen and not fulscreen doesnt seem to work

**Comment by James22rx** [comment]
tell me what u did to make that happen
idek how to do it

**Comment by James22rx** [comment]
what computer is yours?

**Comment by James22rx** [comment]
if its a macbook your refresh rate might be locked at 60

**Comment by dtbMilan** [comment]
bro idek how to use this new version lol

**Comment by grrrrrrbear** [comment]
> if its a macbook your refresh rate might be locked at 60

i play on an imac

**Comment by grrrrrrbear** [comment]
do i try reinstall roblox and restart my pc

**Comment by James22rx** [comment]
@lanylow pls help us we dunno how to use the new version

**Comment by James22rx** [comment]
hi guys i think i found the issue

**Comment by James22rx** [comment]
go into roblox and go into contents (in applications tab) and when ur in press 'macOS' rename the file inside that to 'RobloxPlayer' not 'Roblox' and it should work

**Comment by grrrrrrbear** [comment]
> 
![Skärmavbild 2022-11-05 kl  16 14 15](https://user-images.githubusercontent.com/87470326/200126805-45a7bbff-064e-4a7c-bb86-ec75c8ffca23.png)

rename 1 2 or 3
