### ISSUE TITLE
Using New Version, it says "Roblox not running" even though it's not supposed to be running.

### ISSUE THREAD

**Issue by Displayeddd** [lanylow/rbxfpsunlocker-osx#109]
![Screen Shot 2022-11-05 at 10 31 56 AM](https://user-images.githubusercontent.com/83935019/200124878-34064a75-2944-4e77-a92f-bdc1acf22677.png)

**Comment by Displayeddd** [comment]
When I run it with roblox open it says this: 
![Screen Shot 2022-11-05 at 10 37 00 AM](https://user-images.githubusercontent.com/83935019/200125088-92d993bd-2dd3-416a-b6bc-f890afb9a52c.png)

**Comment by russiakick3000** [comment]
> When I run it with roblox open it says this: ![Screen Shot 2022-11-05 at 10 37 00 AM](https://user-images.githubusercontent.com/83935019/200125088-92d993bd-2dd3-416a-b6bc-f890afb9a52c.png)

same man

**Comment by lanylow** [comment]
Why do you have a backslash after rbxfpsunlocker_osx?

**Comment by Displayeddd** [comment]
Think it was because I had multiple downloads of them. I deleted the previous ones and did it again but still got the same result.
![Screen Shot 2022-11-05 at 11 44 13 AM](https://user-images.githubusercontent.com/83935019/200128156-f32c2443-897b-4e5a-b298-a5b806580518.png)

**Comment by lanylow** [comment]
Your command is still wrong, it's supposed to end with `rbxfpsunlocker_osx 0 -r` as written in the instructions.
