### ISSUE TITLE
exception:roblox is not running

### ISSUE THREAD

**Issue by IceBearIscool** [lanylow/rbxfpsunlocker-osx#112]
Roblox is suppose to be not running 
<img width="565" alt="Screen Shot 2022-11-06 at 12 46 58 AM" src="https://user-images.githubusercontent.com/117530516/200128310-b1b814ea-62d5-4cdf-a4f4-a99f273f3eb2.png">

**Comment by kyla0001** [comment]
for me it worked by not putting the -r. after you put the sudo /Users/myuser/Desktop/rbxfpsunlocker_osx 0 do not click enter yet. open roblox and load into a game and then click enter and it should work.

**Comment by russiakick3000** [comment]
> for me it worked by not putting the -r. after you put the sudo /Users/myuser/Desktop/rbxfpsunlocker_osx 0 do not click enter yet. open roblox and load into a game and then click enter and it should work.

nah for me it just says exception: base_process constructor failed.

**Comment by 3Percs4Zoid** [comment]
> > for me it worked by not putting the -r. after you put the sudo /Users/myuser/Desktop/rbxfpsunlocker_osx 0 do not click enter yet. open roblox and load into a game and then click enter and it should work.
> 
> nah for me it just says exception: base_process constructor failed.

check out the new update it will tell u what to do

**Comment by gunnajsu** [comment]
kyla do u put the ./before sudo or no

**Comment by lanylow** [comment]
Which version of macOS are you using?

**Comment by IceBearIscool** [comment]
> 

Monterey

**Comment by IceBearIscool** [comment]
> > for me it worked by not putting the -r. after you put the sudo /Users/myuser/Desktop/rbxfpsunlocker_osx 0 do not click enter yet. open roblox and load into a game and then click enter and it should work.
> 
> nah for me it just says exception: base_process constructor failed.

same
