### ISSUE TITLE
so i learned how to use the new fps unlocker but i dont know what to do when im on this part?

### ISSUE THREAD

**Issue by gunnajsu** [lanylow/rbxfpsunlocker-osx#118]
![Screenshot 2022-11-05 at 10 48 33 AM](https://user-images.githubusercontent.com/115434137/200134049-d06b54c8-cf54-476e-8dfd-6e69b1ecc161.png)

**Comment by lanylow** [comment]
You have it written on the screen. Type in 0 at the end of the command.

**Comment by gunnajsu** [comment]
> You have it written on the screen. Type in 0 at the end of the command.

thank you bro you bro finally

**Comment by IceBearIscool** [comment]
> 

what did u do?

**Comment by IceBearIscool** [comment]
i cant get past this part
