### ISSUE TITLE
Abort trap: 6

### ISSUE THREAD

**Issue by IncognitoManO** [lanylow/rbxfpsunlocker-osx#12]
when y try to execute any command or the app file it just say:

libc++abi: terminating with uncaught exception of type std::runtime_error: Failed to get Rloblox process info.
Abort trap: 6

**Comment by ztik** [comment]
Is your roblox running, If not launch roblox then run fps unlocker.

**Comment by MrGASPIXX** [comment]
So, do I run Roblox first or the fps unlocked first?

**Comment by ztik** [comment]
> So, do I run Roblox first or the fps unlocked first?

Youn run roblox first.

**Comment by IncognitoManO** [comment]
> > So, do I run Roblox first or the fps unlocked first?
> 
> You run roblox first.

oh k, thanks
