### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by Corkydoodaa** [lanylow/rbxfpsunlocker-osx#120]
Just downloaded the fpsunlocker terminal file and tried to run it with the appropriate command but I'm receiving segmentation error 11 from it.

Can anyone give advice?

![Screen Shot 2022-11-06 at 9 07 08 am](https://user-images.githubusercontent.com/117546161/200143145-d8ec2387-1157-4c97-9503-57436392af56.png)

**Comment by Corkydoodaa** [comment]
Also, this is the latest version.

**Comment by lanylow** [comment]
I don't really know what to tell you, something might be wrong with your operating system.
