### ISSUE TITLE
Fps unlocker

### ISSUE THREAD

**Issue by davilili** [lanylow/rbxfpsunlocker-osx#121]
After I type in *sudo /Users/MyUser/Downloads/rbxfpsunlocker_osx 0 -r* with the actual credentials, it doesn't say successfully set, nor does it say failed. Nothing happens. It brings me back to the cd (Location) place.

**Comment by AR7AS** [comment]
I have this problem as well, After I input the command it ceases to exist. Even tho, I am on macOS Monterey.

**Comment by lanylow** [comment]
That's the intended behavior. After that you can open Roblox and use the unlocker the same way as before.
