### ISSUE TITLE
Command Not Found

### ISSUE THREAD

**Issue by davilili** [lanylow/rbxfpsunlocker-osx#122]
<img width="570" alt="Screenshot 2022-11-05 at 8 42 44 PM" src="https://user-images.githubusercontent.com/117550325/200148835-33634c71-2863-4a09-b3d2-563614aedfd3.png">

**Comment by grrrrrrbear** [comment]
I got the same problem i would like need a propperly video tutorial to understand

**Comment by probabalyJackie** [comment]
delete _osx on the file and command

**Comment by probabalyJackie** [comment]
rename the file to rbxfpsunlocker without the _osx  and from your command

**Comment by davilili** [comment]
wdym im confused?

**Comment by SeizureSaladd** [comment]
Brain issue not broken
