### ISSUE TITLE
*NOT AN ISSUE* Quick tip for people wanting to use the 1.20 version after the security change

### ISSUE THREAD

**Issue by spiriteds** [lanylow/rbxfpsunlocker-osx#127]
I tried the 2.0.1 version, followed all the steps in the readme file, I managed to get the code seemingly working in Terminal, but it didn't work in the actual game, my fps was still capped at 60, then I decided to turn on the 1.20 version (the one with the more user-friendly interface) and the fpsunlocker worked perfectly fine. Seems like if you run both programs at the same time it works and fixes the "unable to get roblox process info" issue.
Hope it helps some people,
Spirit

**Comment by spiriteds** [comment]
Would be useful to create a 1.2.1 version with that fix but this is a tiny bit tedious but still works

**Comment by lanylow** [comment]
The `-r` option exists only to fix that issue, not to unlock the frame rate. The problem you described was caused by not reading the instructions from
the latest release to the end.

**Comment by spiriteds** [comment]
> The `-r` option exists only to fix that issue, not to unlock the frame rate. The problem you described was caused by not reading the instructions from the latest release to the end.

Yeah that was my bad, quick question, do you guys ever plan on bringing the user-friendly interface back? The one that shows up in the top right corner where you can avoid all the coding part and just select the desired fps amount?
