### ISSUE TITLE
won't work

### ISSUE THREAD

**Issue by zu120** [lanylow/rbxfpsunlocker-osx#128]
I tried everything, i even copy and pasted the command but it doesn't work, i put the caps limit to 0 and put -s and -r but it wont workkkk

**Comment by probabalyJackie** [comment]
because your screen is 60 hz?? maybe??

**Comment by probabalyJackie** [comment]
what does it say

**Comment by spiriteds** [comment]
1. go in terminal 
2. type "cd" + where the fpsunlocker is, ex: "cd desktop" or "cd downloads" then press enter
3. paste the command, for example, if the file is in the desktop and you want a cap of 120 fps, paste this " sudo /Users/MyUser/Desktop/rbxfpsunlocker_osx 120 -r", then press enter
4. type in your password, even though you dont see it being typed, you are still typing, then press enter.
that should work, but I prefer to then launch the 1.20 version to make sure it always works

**Comment by russiakick3000** [comment]
> 1. go in terminal
> 2. type "cd" + where the fpsunlocker is, ex: "cd desktop" or "cd downloads" then press enter
> 3. paste the command, for example, if the file is in the desktop and you want a cap of 120 fps, paste this " sudo /Users/MyUser/Desktop/rbxfpsunlocker_osx 120 -r", then press enter
> 4. type in your password, even though you dont see it being typed, you are still typing, then press enter.
>    that should work, but I prefer to then launch the 1.20 version to make sure it always works

Are you on ventura?

**Comment by spiriteds** [comment]
yea

**Comment by lanylow** [comment]
Please see the video I added to the release.
