### ISSUE TITLE
Keeps saying " exception: This application has to be ran as root. " any help?

### ISSUE THREAD

**Issue by 3Percs4Zoid** [lanylow/rbxfpsunlocker-osx#129]
Im on mac m1 ventura and i thought it was because my system wasnt updated but that wasnt the case
![Screenshot 2022-11-05 at 12 32 14 PM](https://user-images.githubusercontent.com/110644332/200154182-449c988a-9b07-4900-8ce2-46a3d6605951.png)

**Comment by lanylow** [comment]
Please read the Setup section in README before posting any issues.
