### ISSUE TITLE
On monterey the latest version doesnt work  (Im using UI)

### ISSUE THREAD

**Issue by Akarilel** [lanylow/rbxfpsunlocker-osx#133]
How do i fix this problem?

**Comment by lanylow** [comment]
Specify what the problem is.

**Comment by Akarilel** [comment]
its the problem with i think process info, i just updated so i think i can fix it from here

**Comment by Akarilel** [comment]
and im using the latest version and im in 12.6.1 on my mac so idk what to do, its just saying out base_process construction failed

**Comment by Akarilel** [comment]
i did everything the video said and it doesnt work

**Comment by wiz23424** [comment]
download version 2.1, run the command shown in the readme, and put -r in front of the command, like this
<img width="565" alt="Screenshot 2022-11-09 at 8 52 17 PM" src="https://user-images.githubusercontent.com/117457899/200870112-27e9617a-578a-4981-942d-3573d06ab3b7.png">
click enter, type in your password and it should be done (remember u need to be in a roblox game while doing this)
