### ISSUE TITLE
Bad CPU type in executable 

### ISSUE THREAD

**Issue by davaax** [lanylow/rbxfpsunlocker-osx#134]
It says "Bad CPU type in executable" after I type in the command 
<img width="562" alt="Screen Shot 2022-11-06 at 1 02 00 PM" src="https://user-images.githubusercontent.com/117594062/200187352-e3bd1bec-6c93-49e2-96cc-95fa8cc70952.png">

**Comment by lanylow** [comment]
What do you get if you run `arch` command?

**Comment by davaax** [comment]
idk what that is

**Comment by lanylow** [comment]
It's a command, you type it into the little hacky console window.
