### ISSUE TITLE
internal error in Code Signing Subsystem

### ISSUE THREAD

**Issue by wiz23424** [lanylow/rbxfpsunlocker-osx#137]
tried unlocking my fps, it shows "internal error in Code Signing Subsystem", dunno what to do (happening in console btw)

<img width="571" alt="Screenshot 2022-11-07 at 9 03 12 PM" src="https://user-images.githubusercontent.com/117457899/200350826-0418dfda-c1b8-4802-8720-94c476227275.png">

**Comment by wiz23424** [comment]
please help guys ive not been able to play roblox properly for like a week now

**Comment by lanylow** [comment]
What macOS version are you on?

**Comment by lanylow** [comment]
Go to Settings > Privacy & Security > App Management and enable Terminal. Run the command again and it should work.

**Comment by wiz23424** [comment]
unlocker is finally working again. thanks man
