### ISSUE TITLE
Won't let me open

### ISSUE THREAD

**Issue by zu120** [lanylow/rbxfpsunlocker-osx#138]
Im on Mac OS Monterey and whenever I try to run the command it says “rbxfpsunlocker_osx” cannot be opened because it is from an unidentified developer." what do I do

**Comment by wiz23424** [comment]
go to settings, go to the privacy and security section, click on it and it will show you this (if ur on macOS monterey)![image](https://user-images.githubusercontent.com/117457899/200868796-c1a5ee21-06f9-469a-ad6c-f422962b8dec.png)

in urs it will show "rbxfpsunlocker couldnt be opened", click on open anyway, paste the command in terminal again. It will ask you if you want to open it, click open, and its done
