### ISSUE TITLE
how to install without an admin account

### ISSUE THREAD

**Issue by JustStr1ke** [lanylow/rbxfpsunlocker-osx#14]
so I saw that you can only access the fps unlocker only with an admin account. if not then it will say "user" is not in the sudoer's file. This incident will be reported. can you fix this quickly since my admin account doesn't have roblox installed and doesn't have the files and recording apps i use. i dont wanna move my recordings and files to the admin account. any help from the developers will be great.

**Comment by lanylow** [comment]
The program has to be ran as sudo, because it uses functions that require elevated privileges. You can't run it as a normal user.

**Comment by JustStr1ke** [comment]
i see so there’s never going to be a fix? im really hoping there’s going to be a fix in the future so ill just wait around

**Comment by lanylow** [comment]
But what do you expect us to fix? It's nothing related to the program, just add your user to the sudoers file and you'll be allowed to use sudo.

**Comment by JustStr1ke** [comment]
oh alr thanks for the help
