### ISSUE TITLE
Straight up wont unlock

### ISSUE THREAD

**Issue by bluzdy** [lanylow/rbxfpsunlocker-osx#140]
everything up to unlocking it works. I put in the command and it just doesnt do anything, no error and no confimation.

**Comment by bluzdy** [comment]
m1 macbook air on monterey 12.3.1

**Comment by lanylow** [comment]
Did you verify if the frame rate changed? Or are you just assuming because it didn't say anything in the terminal?

**Comment by bluzdy** [comment]
it says 60fps on roblox

**Comment by ai-h24** [comment]
> i type the command and terminal doesn’t ask for a password, doesn’t say anything after i use it and roblox doesn’t unlock

what is the command you are typing? and did u use sudo before u typed that command? and can u verify if the unlocker is working by limiting ur fps to something that is less than 60fps? like 30 or any value just to make sure if the unlocker works on not. 

try both commands:
`sudo /Applications/rbxfpsunlocker_osx 0` to get unlimited fps
and
`sudo /Applications/rbxfpsunlocker_osx 30` to make sure the unlocker works or not. 

or just open a new terminal window type `sudo` then drag and drop wherever the unlocker is located then add `0 or 30`

also **note** that MacOS Ventura has a bug where it locks your FPS to ur monitor refresh rate and m1 MacBook air is limited to 60hz/60FPS, but if u are using an external monitor that has a higher refresh rate then u should be fine. but still the FPS will be locked to ur external monitor display refresh rate.

**Comment by bluzdy** [comment]
>
> i have done all of this, my main monitor is 120hz, im using the command

sudo /Users/Name/Downloads/rbxunlocker_osx 130

**Comment by ai-h24** [comment]
ur not really giving me much information here, so be more specific again. ur saying u have tried the 30 fps command i mentioned above and it didn't work, correct? just the same "issue" nothing happens. right?

**Comment by bluzdy** [comment]
I don’t know how i could be more specific.
I’ve said my version, laptop model and the command i’m putting in. I’ve
tried putting in lower fps but the same outcome happens.
It doesn’t ask for a password, the command says it went through because
there was no error message. It just doesn’t unlock

**Comment by themagictool** [comment]
same here

**Comment by Trashyyy396** [comment]
Yea same goes for me i did all of it and the process completed but my fps would not go up from 30 to 120(the fps i had set for roblox)

**Comment by undyuuang** [comment]
you need to type 
cd **insert file location**
first
