### ISSUE TITLE
roblox just updated and it doesnt work again 

### ISSUE THREAD

**Issue by probabalyJackie** [lanylow/rbxfpsunlocker-osx#142]
it used to work yesterday after the signature remove commands thing and then it just updated and doesnt work again

i tried the two commands, redownloaded the unlocker and stuff just doesnt work again

**Comment by lanylow** [comment]
It does?
![image](https://user-images.githubusercontent.com/31806776/200944140-d4773e7a-2558-4f1a-bd6e-a3f3482f2ea2.png)

**Comment by Stxtically** [comment]
works for me

**Comment by probabalyJackie** [comment]
oh it works again

**Comment by Eross675** [comment]
As soon as I got home from school and got on roblox I tried to play a game, roblox updated, and then fps unlocker stopped working.
