### ISSUE TITLE
I cannot join a Roblox game without the fps unlocker closing

### ISSUE THREAD

**Issue by cona1919** [lanylow/rbxfpsunlocker-osx#144]
<img width="256" alt="Screen Shot 2022-11-09 at 8 46 29 PM" src="https://user-images.githubusercontent.com/117875832/200980905-b9b4a40c-42ea-4f01-bc1e-574c3ca3bcdd.png">

**Comment by ai-h24** [comment]
use the terminal version. 
if u need help let me know. the gui version is broken for now.
