### ISSUE TITLE
exception: base_process constructor failed.

### ISSUE THREAD

**Issue by cxzxs** [lanylow/rbxfpsunlocker-osx#145]

**Comment by cxzxs** [comment]
![c69aa09a-dcc6-4377-a1d5-8457c0c22a68](https://user-images.githubusercontent.com/117915896/201095714-4597b1d4-5766-4033-94de-ff4f04504a41.jpg)

**Comment by ai-h24** [comment]
### try:
running this command before opening roblox `sudo /Applications/rbxfpsunlocker_osx 0 -r`

then run this command after roblox is opened `sudo /Applications/rbxfpsunlocker_osx 0`
### let me know if that works. 

_note:
if that worked, you do NOT have to re-do this steps each time just the first time.
so, after you do this once just use `sudo /Applications/rbxfpsunlocker_osx 0` like you do normally._

**Comment by DownBeatGnu7882** [comment]
Worked! I don't get any error messages now but I'm still capped at 60 fps. I guess Ventura messed it up.

**Comment by russiakick3000** [comment]
> Worked! I don't get any error messages now but I'm still capped at 60 fps. I guess Ventura messed it up.

Yeah same with me man, just the down side of going with apple. Always screwing stuff up.

**Comment by DownBeatGnu7882** [comment]
> > Worked! I don't get any error messages now but I'm still capped at 60 fps. I guess Ventura messed it up.
> 
> Yeah same with me man, just the down side of going with apple. Always screwing stuff up.

Yup.

**Comment by ai-h24** [comment]
> Worked! I don't get any error messages now but I'm still capped at 60 fps. I guess Ventura messed it up.

glad to hear that. also me and a few friends currently looking for a fix for Ventura fps cap, and did also contact apple about it. 

nothing worked yet but hopefully soon we'll find a workaround.

**Comment by DownBeatGnu7882** [comment]
> > Worked! I don't get any error messages now but I'm still capped at 60 fps. I guess Ventura messed it up.
> 
> glad to hear that. also me and a few friends currently looking for a fix for Ventura fps cap, and did also contact apple about it.
> 
> nothing worked yet but hopefully soon we'll find a workaround.

Got it, thank you.
