### ISSUE TITLE
followed every step from lanylow video and still doesnt work 

### ISSUE THREAD

**Issue by 3Percs4Zoid** [lanylow/rbxfpsunlocker-osx#146]
![Screen Shot 2022-11-10 at 9 08 37 PM](https://user-images.githubusercontent.com/110644332/201246964-3608838b-6fcc-4203-b12c-5ac71d9b42a1.png)
im on imac m1 monterey

**Comment by ai-h24** [comment]
### try:
running this command before opening roblox `sudo /Applications/rbxfpsunlocker_osx 0 -r`

then run this command after roblox is opened `sudo /Applications/rbxfpsunlocker_osx 0`
### let me know if that works. 

_note:
if that worked, you do NOT have to re-do this steps each time just the first time.
so, after you do this once just use `sudo /Applications/rbxfpsunlocker_osx 0` like you do normally._
