### ISSUE TITLE
at this point it just doesn't work

### ISSUE THREAD

**Issue by kyla0001** [lanylow/rbxfpsunlocker-osx#148]
![Screenshot 2022-11-11 at 9 03 46 PM](https://user-images.githubusercontent.com/117529819/201451564-644a01f2-debc-49a8-a193-aa5236828753.jpeg)

**Comment by kyla0001** [comment]
It was working fine 3 days ago, came back from my break and its just not working, so I'm not sure what's wrong with it.

**Comment by lanylow** [comment]
Which macOS version are you using?

**Comment by kyla0001** [comment]
When i submitted this i was using macOS Ventura 13.0, but i got an update last night and now I'm on macOS Ventura 13.0.1. I'm gonna try to use it on this version to see if it works or not.

**Comment by kyla0001** [comment]
Yeah, now it's working. It had to be something about the update itself cause I did the exact thing last night and it wasn't working which is weird.

**Comment by lanylow** [comment]
Go to Settings > Privacy & Security > App Management and enable Terminal.

**Comment by russiakick3000** [comment]
> Yeah, now it's working. It had to be something about the update itself cause I did the exact thing last night and it wasn't working which is weird.

Are you using a external monitor?

**Comment by kyla0001** [comment]
umm I have a monitor connected to my mac laptop yeah
