### ISSUE TITLE
help.

### ISSUE THREAD

**Issue by xmasdrip** [lanylow/rbxfpsunlocker-osx#152]
Lany low or someone else, can you help me find app management? I checked in privacy and security and there was nothing.  Please help, thanks.

**Comment by ai-h24** [comment]
idk what MacOS ur on but on Ventura here it is:

![App Management](https://user-images.githubusercontent.com/117847131/201512830-ae6a9600-1776-4c02-9ed1-b0bbcf596ea9.png)

**Comment by xmasdrip** [comment]
> idk what MacOS ur on but on Ventura here it is:
> 
> ![App Management](https://user-images.githubusercontent.com/117847131/201512830-ae6a9600-1776-4c02-9ed1-b0bbcf596ea9.png)

Yes Im on mojave but i checked there and its not there.

**Comment by xmasdrip** [comment]
I still cant find it

**Comment by lanylow** [comment]
It might be called Full Disk Access.
