### ISSUE TITLE
"no such file or directory"

### ISSUE THREAD

**Issue by nayx678** [lanylow/rbxfpsunlocker-osx#154]
![Screen Shot 2022-11-14 at 4 22 59 PM](https://user-images.githubusercontent.com/118230336/201795858-876e4ff4-3dbb-46d1-ac34-f418f93fd444.png)

**Comment by SeizureSaladd** [comment]
do you even have roblox installed

**Comment by lanylow** [comment]
Run these two commands:
`/usr/bin/codesign --remove-signature ~/Applications/Roblox.app/Contents/MacOS/RobloxPlayer`
`/usr/bin/codesign --remove-signature ~/Applications/Roblox.app/Contents/MacOS/Roblox.app/Contents/MacOS/Roblox`
