### ISSUE TITLE
base_process constructor failed/unable to detect roblox is open

### ISSUE THREAD

**Issue by reconzt** [lanylow/rbxfpsunlocker-osx#155]
![base](https://user-images.githubusercontent.com/118263268/201891711-f14a2565-fdb3-4421-9e5e-40e6bebf9b98.png)
![detection failure](https://user-images.githubusercontent.com/118263268/201891720-9cd74fe3-38f4-42de-a3da-9ec2eaf61183.png)

I honestly am not sure what version I'm using but since the old one stopped working at around Halloween I tried one of the latest versions but it still didn't work, heard people saying it was due to a roblox security update but if possible, is there a version you know for sure works? If there isn't a working version still let me know, thank you

**Comment by lanylow** [comment]
Read the latest release.
