### ISSUE TITLE
zsh -80x24

### ISSUE THREAD

**Issue by spicykeyyss** [lanylow/rbxfpsunlocker-osx#158]
<img width="565" alt="Screenshot 2022-11-17 at 14 17 45" src="https://user-images.githubusercontent.com/109385752/202470088-2d3272f5-9b93-4001-a7b4-6068df6b99b8.png">

whenever i try to use the fps unlocker it says zsh-80x24 instead of giving me the option to type the password idk what to do pls help

This is console btw

**Comment by lanylow** [comment]
If you type in the password once, you don't have to do it again for some time.
