### ISSUE TITLE
i followed the instructions but still its stuck on 60 fps

### ISSUE THREAD

**Issue by eren43242** [lanylow/rbxfpsunlocker-osx#159]

**Comment by ai-h24** [comment]
If you are on macOS Ventura, then the fps is always locked on ur monitor refresh rate. and cannot be unlocked over it (at least for now there is no such a way to do so).

**Comment by russiakick3000** [comment]
> If you are on macOS Ventura, then the fps is always locked on ur monitor refresh rate. and cannot be unlocked over it (at least for now there is no such a way to do so).

Do you ever think there will be a work around for the lock or nah

**Comment by eren43242** [comment]
ok thnks

**Comment by ai-h24** [comment]
> > If you are on macOS Ventura, then the fps is always locked on ur monitor refresh rate. and cannot be unlocked over it (at least for now there is no such a way to do so).
> 
> Do you ever think there will be a work around for the lock or nah

for sure. at some point there will be a way to unlock the fps cap (from apple) or some workaround, i had an idea few days ago of a "possibility" of a way to unlocking it so i am gonna go work on it now and see how everything goes. ill update u when i’m done the testings.

**Comment by ai-h24** [comment]
i have high hopes and hopefully the fix i’m thinking of will work, we will see.

**Comment by ai-h24** [comment]
> i have high hopes and hopefully the fix i’m thinking of will work, we will see.

little update: 
i was able to somewhat disable the fps cap. also i tried this on an m1 machine (MacOS Ventura) and a 240hz monitor, i am still doing testing and trying to figure out how to completely disable VSync.

Before: 
![1](https://user-images.githubusercontent.com/117847131/203012426-1124c3d2-8551-4fc8-879d-c56b52437a76.jpeg)

After:
![2](https://user-images.githubusercontent.com/117847131/203012396-3790da91-65b7-4094-ac2e-900a0b4965a6.jpeg)

**Comment by eren43242** [comment]
oh ok
