### ISSUE TITLE
2.0.1 latest fpsunlocker not working on M1

### ISSUE THREAD

**Issue by Agony0909** [lanylow/rbxfpsunlocker-osx#160]
the issue was: 

/Applications/Roblox.app/Contents/MacOS/RobloxPlayer: internal error in Code Signing subsystem

Im wondering what i should do to fix this.
please help!

**Comment by ai-h24** [comment]
put this in terminal:

```
sudo /usr/bin/codesign --remove-signature /Applications/Roblox.app

sudo /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/CrashpadHandlerExe

sudo /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/RobloxPlayer  

sudo /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/Roblox.app

sudo /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/Roblox.app/Contents/MacOS/Roblox

```

type ur password, click enter and the error "base_process constructor failed" will go away. then just open roblox and use the FPS Unlocker like u normally do.

let me know if that works for you.
