### ISSUE TITLE
base_process constructor failed

### ISSUE THREAD

**Issue by noefaeL** [lanylow/rbxfpsunlocker-osx#161]
<img width="316" alt="Screen Shot 2022-11-21 at 14 30 46" src="https://user-images.githubusercontent.com/118711100/202972997-f5c391e4-f48c-416a-b2a0-cd12d5233132.png">
This is on the **non-UI** branch, tried running the code but only got this even after quitting and restarting.

**Comment by ai-h24** [comment]
put this in terminal:

```
sudo /usr/bin/codesign --remove-signature /Applications/Roblox.app

sudo /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/CrashpadHandlerExe

sudo /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/RobloxPlayer  

sudo /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/Roblox.app

sudo /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/Roblox.app/Contents/MacOS/Roblox

```

type ur password, click enter and the error "base_process constructor failed" will go away. then just open roblox and use the FPS Unlocker like u normally do.

let me know if that works for you.

**Comment by noefaeL** [comment]
Thanks for the reply - unfortunately the same error pops up after the commands.

**Comment by ai-h24** [comment]
> Thanks for the reply - unfortunately the same error pops up after the commands.

did u close Roblox, then run all the commands above? then opened roblox and tried the fps unlocking command? 
such as this command:
`sudo /Applications/rbxfpsunlocker_osx 0`

and yet the error still occurred? could u try again?

**Comment by ai-h24** [comment]
and if that doesn't work again. try giving terminal "full desk access" 
![1](https://user-images.githubusercontent.com/117847131/203047405-3e5f2e5f-c1d9-4cbc-9112-d38d9a0fe9c5.png)
then add terminal to it and try again, good luck.

**Comment by ai-h24** [comment]
> Still happens. It worked for a little bit but I think the new Roblox update screwed up again.

re-do the steps i told u to do before.
