### ISSUE TITLE
120fps cap 

### ISSUE THREAD

**Issue by pierrelee12** [lanylow/rbxfpsunlocker-osx#162]
Using this fps unlocked, it has allowed my fps to go from 60 to 120, which I am really grateful about.

However, I think it was mentioned before that the 120 fps cap issue would be solved, I'm not sure If it has been done yet? Just wanted to check in, as I saw on lanylow's video that he had 140fps on his Mac, while I am still on 120.

Any help would be appreciated. Thank you!

**Comment by ai-h24** [comment]
if ur not on macOS Ventura use "Quartz Debug" app (can be downloaded from apple developer website) just search for `Additional Tools for Xcode` Download it, open it then click graphics folder and open the Quartz Debug app.

then click "command + 1" and you'll see this: 
![a](https://user-images.githubusercontent.com/117847131/203781111-b03f64cf-696d-46dd-a9ff-58d16f7b4b0b.png)

now un-check the "Enable Vertical Sync" option aka VSync (like the image under) and enjoy uncapped frames over 120 FPS. 

![b](https://user-images.githubusercontent.com/117847131/203781177-229dd881-9a05-483a-8cc5-d1f219eb7d9c.png)

**Comment by pierrelee12** [comment]
thank you!

Unfortunately, after updating my Mac to Ventura, I'm somehow back at 60fps, not even experiencing 120fps anymore.

Help? :(

**Comment by ai-h24** [comment]
youtube this (downgrade from ventura to monterey without losing data)

**Comment by pierrelee12** [comment]
Has a fix for this been created yet? the fps unlocked not working for ventura
