### ISSUE TITLE
Macos Ventura

### ISSUE THREAD

**Issue by 1Castiel** [lanylow/rbxfpsunlocker-osx#165]
Any idea when it will be fixed for macos ventura? The issue where the fps is locked to your mac's display refresh rate.

**Comment by TruckDriver56** [comment]
yeah im the exact same its really irritating

**Comment by TruckDriver56** [comment]
i was wondering if it is something any of the developers on the fps unlocker can fix or if its just a problem that will stick

**Comment by lanylow** [comment]
There is no issue because the unlocker works on ventura, if you want to go above your display's refresh rate contact Roblox and tell them to disable display sync in Metal. ¯\_(ツ)_/¯

**Comment by TruckDriver56** [comment]
should i say to roblox that i want them to disable my display sync in metal??
