### ISSUE TITLE
It does not work pls help

### ISSUE THREAD

**Issue by iicecey** [lanylow/rbxfpsunlocker-osx#168]
![Screenshot 2022-12-09 at 6 48 39 PM](https://user-images.githubusercontent.com/120227859/206813691-b4b63787-80a3-4142-bf59-f8e9a295008c.png)

**Comment by Matt-design542** [comment]
close roblox and type sudo /Users/MyUser/Downloads/rbxfpsunlocker_osx 999 -r and it should work after

**Comment by iicecey** [comment]
does not work
<img width="553" alt="Screenshot 2022-12-10 at 10 22 53 AM" src="https://user-images.githubusercontent.com/120227859/206862486-0e792a47-21f8-4f73-aa44-9b01b8a93d46.png">

**Comment by Matt-design542** [comment]
remember to replace "MyUser" with ur user

**Comment by iicecey** [comment]
still does not work
![Screenshot 2022-12-10 at 6 08 49 PM](https://user-images.githubusercontent.com/120227859/206878831-80408dce-b37e-46a3-87fe-d4e5a502ab3c.png)

**Comment by Matt-design542** [comment]
idk anymore this is my last attempt do -r while roblox closed then open and remove the -r

**Comment by iicecey** [comment]
well then it still does not work

**Comment by iicecey** [comment]
would work if the unblocker gets updated?

**Comment by lanylow** [comment]
Run these two commands and try using the unlocker:
`/usr/bin/codesign --remove-signature ~/Applications/Roblox.app/Contents/MacOS/RobloxPlayer`
`/usr/bin/codesign --remove-signature ~/Applications/Roblox.app/Contents/MacOS/Roblox.app/Contents/MacOS/Roblox`

**Comment by iicecey** [comment]
<img width="573" alt="Screenshot 2022-12-24 at 12 22 06 PM" src="https://user-images.githubusercontent.com/120227859/209445920-84220894-6cdd-4f3c-94c7-7d8b39193108.png">


still does not work

**Comment by lanylow** [comment]
You will have to find where Roblox is installed on your mac and adjust these commands accordingly.

**Comment by iicecey** [comment]
wydm by adjust commads accordingly?

**Comment by lanylow** [comment]
Change the path used in the command.
