### ISSUE TITLE
FPS Unlocker Issue on New Version Ventura 13.1

### ISSUE THREAD

**Issue by zixqou** [lanylow/rbxfpsunlocker-osx#172]
I'm pretty sure its because of the new version. Before I updated on my mac, the unlocker is still working (if curious, the update that I was in b4 the issue was (ver 12.3). And then when I updated it to ver 13.1 Ventura it doesn't work anymore bruh 😿 I hope they fix this bc I'm getting sh*tty framerate drops on games. 

(Im on my Mac M1) 
<img width="252" alt="Screenshot 2022-12-17 at 11 56 05 PM" src="https://user-images.githubusercontent.com/120803969/208250448-2de6df4d-71f1-4c7b-9bcd-5ae655a63c07.png">

**Comment by lanylow** [comment]
Read the latest release.
