### ISSUE TITLE
"cannot be opened because it is from an unidentified developer"

### ISSUE THREAD

**Issue by juliuwulooooolll** [lanylow/rbxfpsunlocker-osx#174]
![Uploading Screenshot 2022-12-22 at 9.33.44 PM.png…]()

**Comment by Matt-design542** [comment]
go into system settings, and find Privacy & Security. When u have got into the location find the Security by scrolling down on later versions but look at the top of the system settings tab. when you find it try opening the fps unlocker again and try find something that looks similar to this
![dummy](https://user-images.githubusercontent.com/72158435/209425171-c6df2720-f75f-41b9-97fd-46aeff883414.png)
idk if this image works though
