### ISSUE TITLE
Abort trap: 6 in version v2.0.1

### ISSUE THREAD

**Issue by awamalaannonymouse** [lanylow/rbxfpsunlocker-osx#175]
when i press enter after doing every step if says cannot load 'rbxfpsunlocker_osx' (load command 0x80000034 is unknown)
Abort trap: 6 why i dont know how to fix help please

**Comment by retardinneedofassistance** [comment]
I have the same issue, ive done about everything i can think of to fix this issue.

**Comment by lanylow** [comment]
What macOS version are you using?

**Comment by awamalaannonymouse** [comment]
my version is 10.13.6

**Comment by lanylow** [comment]
I don't support old macOS versions.

**Comment by awamalaannonymouse** [comment]
oh how do i get older version

**Comment by awamalaannonymouse** [comment]
how do i update to a newer version

**Comment by lanylow** [comment]
You go to settings and find software update or something.
