### ISSUE TITLE
Error - /Applications/Roblox.app/Contents/MacOS/RobloxPlayer: No such file or directory

### ISSUE THREAD

**Issue by sourcecodemaker763** [lanylow/rbxfpsunlocker-osx#179]
Anytime I run the command sudo /Users/Dare/Downloads/rbxfpsunlocker_osx 999 -r, it gives me the error /Applications/Roblox.app/Contents/MacOS/RobloxPlayer: No such file or directory. I don't understand why this happens. It then just wont unlock the fps and still stay stuck at 30-40 frames even though I those 999. I know there isn't anything wrong with the command, its just that it tries to go find a file that doesn't exist. Think you can fix this?

The version is v2.0.1, aka the latest version as of Jan 14 2023.

I think there is a problem in the code, I might be able to fix it if someone could tell me how to modify the code for this program. I don't know much about macOS software, but I think I can solve it. All I know its an annoying issue.

**Comment by lanylow** [comment]
Firstly, if you're getting 30-40 frames in Roblox I don't know what the point of using this program is, because your mac clearly can't even handle 60. Addressing the problem, you have Roblox installed in a different location than most people do, so you'd have to change the path in code in order for it to work.

**Comment by sourcecodemaker763** [comment]
How do you change the path?

**Comment by sourcecodemaker763** [comment]
> Firstly, if you're getting 30-40 frames in Roblox I don't know what the point of using this program is, because your mac clearly can't even handle 60. Addressing the problem, you have Roblox installed in a different location than most people do, so you'd have to change the path in code in order for it to work.



Your actually right, it started working but my fps isn't increasing.

**Comment by lanylow** [comment]
This program is only removing the 60 fps cap, it won't magically make your mac perform better.
