### ISSUE TITLE
it dosent work

### ISSUE THREAD

**Issue by Bedwarsmaster** [lanylow/rbxfpsunlocker-osx#180]
I did the code and everything but I still cap at 60 fps not 999-120

**Comment by Bedwarsmaster** [comment]
and it docent say anything act a error

**Comment by lanylow** [comment]
What macOS version are you using?

**Comment by Bedwarsmaster** [comment]
@lanylow it only works when I'm not in full screen

**Comment by lanylow** [comment]
Yeah, I know about that.
