### ISSUE TITLE
logic_error: Failed to get Roblox process info, Make sure Roblox is open and try again

### ISSUE THREAD

**Issue by sraj07** [lanylow/rbxfpsunlocker-osx#181]
`logic_error: Failed to get Roblox process info.
Make sure Roblox is open and try again.`

I keep getting this error despite having roblox up and running, and I even tried reopening both Roblox and the terminal but to no avail. 

What I am typing word for word is `sudo ./rbxfpsunlocker 123`

**Comment by lanylow** [comment]
Read the latest release.
