### ISSUE TITLE
doesnt unlock, no error or anything

### ISSUE THREAD

**Issue by universalcats2237** [lanylow/rbxfpsunlocker-osx#182]
hi so i have used this fps unlocker before and had it work however i uninstalled it. trying to get it up and running again now and it doesnt work
<img width="534" alt="Screen Shot 2023-01-27 at 6 23 11 pm" src="https://user-images.githubusercontent.com/123725508/215040817-68b807e1-7eaa-43b8-bc43-4b22a89ac48c.png">

as seen in the picture after entering my password it just comes up with a blank line underneath. no confirmation, no error and doesnt unlock in game.

i am running mac m1 monterey with 8gb memory.

not sure if im stupid and misunderstanding steps but id appreciate some help with this.

**Comment by lanylow** [comment]
What version of monterey exactly are you using? Is it the 12.6.3 that came out recently?

**Comment by universalcats2237** [comment]
12.0.1

**Comment by blackxfiied** [comment]
same, but for me it's with macOS Ventura 13.2
I think it's the Roblox build. maybe they patched the FPS unlocked or something?

**Comment by molfux** [comment]
im hеre to help so listen
you probably dont have the roblox in your "applications" folder just like me
get the roblox, put it in app's folder and use the fps unlocker it will ride smoothly

**Comment by gostgamer6166** [comment]
mine is in the app folder and it comes with the same thing 
<img width="574" alt="Screenshot 2023-07-17 at 5 05 03 PM" src="https://github.com/lanylow/rbxfp
<img width="769" alt="Screenshot 2023-07-17 at 5 05 29 PM" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/69414114/2030e48e-af50-4c79-8be6-042e28ad869d">
sunlocker-osx/assets/69414114/a1135004-4e6c-4c87-91f2-fa43a4a0ca4d">

**Comment by lanylow** [comment]
Read new instructions on the [script branch](https://github.com/lanylow/rbxfpsunlocker-osx/tree/script).
