### ISSUE TITLE
Does not work, no errors shown or anything

### ISSUE THREAD

**Issue by Maxnoobbie123** [lanylow/rbxfpsunlocker-osx#183]
My MacOS Version is an M1 Ventura 13.1
![Screenshot 2023-02-14 at 5 35 08 PM](https://user-images.githubusercontent.com/74038847/218697815-986dd9bc-db80-40b4-a57d-51b0afa90a5e.png)

**Comment by Maxnoobbie123** [comment]
just in case a full screenshot is needed here it is with me retrying 
![Screenshot 2023-02-14 at 8 02 27 PM](https://user-images.githubusercontent.com/74038847/218734161-a1cac4f8-e85e-4a53-b754-01678b55da8a.png)

**Comment by lanylow** [comment]
If you're trying to unlock studio use only -s. Also if you're on ventura you won't get more fps than your display supports.
