### ISSUE TITLE
It doesn't works please help

### ISSUE THREAD

**Issue by Aizen90** [lanylow/rbxfpsunlocker-osx#184]
After I put my password on it, it says these "dyld: cannot load 'rbxfpsunlocker_osx' (load command 0x80000034 is unknown)" please help me how to fix this my laptop is on an old version and I don't know if it does work on the old version

**Comment by lanylow** [comment]
What version are you on exactly?

**Comment by Aizen90** [comment]
it's just an old laptop the last version of this worked for me, but now this new version doesn't work for me anymore 
this is just version 10.10.5.

**Comment by lanylow** [comment]
Sorry, but I don't support old macOS releases. Current code of the unlocker is just simply too modern to compile on older versions.

**Comment by lanylow** [comment]
Since you said older versions worked, you can try running this command and then using the old unlocker. `/usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/RobloxPlayer`

**Comment by Aizen90** [comment]
did you mean the old fps unlocker like the old version of it

**Comment by Aizen90** [comment]
but is there still any chance that it would still work using the older version of this

**Comment by lanylow** [comment]
I literally told you what to do to make it work.
