### ISSUE TITLE
won't unlock

### ISSUE THREAD

**Issue by heidixmarie** [lanylow/rbxfpsunlocker-osx#187]
the fps unlocker works sometimes but most of the time it decides not to work and will not show an error, it'll ask for my password but when i go in game i'm capped to 60 even tho i do sudo /Users/myuser/Desktop/rbxfpsunlocker_osx 250 -r or i put 0 to do unlimited. it works for a few days but when roblox updates it stops working. it's an issue thats been happening for weeks.

**Comment by lanylow** [comment]
Read the latest release or watch the video linked in it.

**Comment by heidixmarie** [comment]
i've just done it step by step again, but it just keeps me at 60fps but i get 144 fps usually when it works.

**Comment by heidixmarie** [comment]
its still not working. i need help

**Comment by SeizureSaladd** [comment]
Are you on Ventura because you need a higher refresh rate monitor
