### ISSUE TITLE
idk if this is a new issue

### ISSUE THREAD

**Issue by big-cheese1** [lanylow/rbxfpsunlocker-osx#189]

**Comment by big-cheese1** [comment]
sooo when i enter the codes for the fps unlocker i run into 2 problems every time that i don't know how to fix, 1st being this red text that says "This application must be ran as root."
 or it just simply wont work not telling me whats wrong because even after i try my best to carefully follow each and every step. 
It still keeps me at 60 fps AND ALSO another thing is i watch the explanation video and i got confused at the one bit where when you entered the game there was this little shaded box that displayed your fps in a green font and im confused what you did to get there so pls help 🙏

**Comment by big-cheese1** [comment]
ok nvm im just dumb BUT im still having trouble with the ui thing in ur video and that "This application must be ran as root."

**Comment by lanylow** [comment]
You must write sudo before the actual command, like I do in the video. The green box can be opened with Shift + F5.

**Comment by big-cheese1** [comment]
ok thank you!

**Comment by big-cheese1** [comment]
also if im on a macOS Ventura is it still possible for me to reach a fps higher then 60?

**Comment by lanylow** [comment]
Yes, if you connect a monitor with higher refresh rate.
