### ISSUE TITLE
Error running FPS unlocker

### ISSUE THREAD

**Issue by cull0** [lanylow/rbxfpsunlocker-osx#190]
I deleted roblox because roblox wasn't working, I re-downloaded roblox and tried to run my fps unlocker and it said "exception: base_process constructer failed", this has happened before many times so I casually did the fix with "sudo /Users/[NAME]/Downloads/rbxfpsunlocker_osx 0 -r" like I always do which always works and it said 

"/Applications/Roblox.app/Contents/MacOS/RobloxPlayer: internal error in Code Signing subsystem"

and this has never ever happened? I am completely confused and I have no idea at all how to fix this??

What does this mean and how do I fix it?

**Comment by cull0** [comment]
<img width="695" alt="Screenshot 2023-02-26 at 18 26 39" src="https://user-images.githubusercontent.com/116982989/221429412-7cb0aa9e-904f-43a1-b20b-d10c20e6a919.png">

I have re-installed the FPS unlocker and I have tried to do the exact same fix with base_process constructer failed blah blah blah and it still said the same '

""/Applications/Roblox.app/Contents/MacOS/RobloxPlayer: internal error in Code Signing subsystem"

**Comment by lanylow** [comment]
If you're on ventura go to Settings > Privacy & Security > App Management and enable terminal, if you're on older versions go to Settings > Privacy & Security > Full Disk Access instead.
