### ISSUE TITLE
Can't get up to 60 fps

### ISSUE THREAD

**Issue by LplayedXD** [lanylow/rbxfpsunlocker-osx#191]
I used the fps unlocker, did all of the instructions, but still can't get above 60 fps (it stays at 60 fps)

**Comment by TAM-Monke** [comment]
> I used the fps unlocker, did all of the instructions, but still can't get above 60 fps (it stays at 60 fps)
I’m not a dev but I just want to tell you that in the read me it says if you want help you have to say if you are using the ui or console version of the fps unlocker

**Comment by LplayedXD** [comment]
I am using the latest version of the FPS unlocker and using macOS Ventura 13.2.1 version. I did everything you said in your video but I can't seem to get above 60 fps. You also mentioned you have to have above 60 frame rate on your mac but I don't know how to do that.

**Comment by LplayedXD** [comment]
> 

I think Im using the UI version

**Comment by lanylow** [comment]
You answered the question yourself. Displays have this specification called refresh rate, which basically defines how many times per second the image will appear on screen. Most Apple devices - including yours - have a 60 Hz display. macOS Ventura syncs the game with the display, which makes it run at 60 FPS. That means you can't do anything about it, unless you connect an external display with higher refresh rate (just to clarify, even though it should work, I don't guarantee anything).

**Comment by LplayedXD** [comment]
> 

Can you give me a tutorial on how to do that?

**Comment by lanylow** [comment]
- Open amazon
- Look for a high refresh rate gaming monitor
- Buy it
- Connect it to your mac
- Set it as the main display in settings
- Pray that it works
