### ISSUE TITLE
Base_process constructor failed

### ISSUE THREAD

**Issue by pierrelee12** [lanylow/rbxfpsunlocker-osx#192]
Anyone else having issues with base_process constructor failed?

no matter what I do the same thing keeps popping up, no idea why.

Any ideas?
<img width="571" alt="Screenshot 2023-03-10 at 11 31 10 PM" src="https://user-images.githubusercontent.com/118976528/224357818-92e32256-6dc4-4437-ab81-aeb3a97bd1d9.png">

**Comment by Azkapop** [comment]
i have a same problem here

**Comment by lanylow** [comment]
Your macOS version is probably too old, if that's not the case then I have no clue how to help.

**Comment by Yoyopizzacat** [comment]
Same issue here but I am on macOS Ventura and it worked previously. Only stopped working after Roblox player update.
