### ISSUE TITLE
Roblox won't open after creating shortcut

### ISSUE THREAD

**Issue by VoidSequencx** [lanylow/rbxfpsunlocker-osx#193]
I created the fps unlocker shortcut, but roblox stopped opening after I tried executing it. I reinstalled roblox and deleted the rbxfpsunlocker-osx file, but roblox wont open (install) at all

**Comment by TAM-Monke** [comment]
I’m not a dev or anything but I’m just curious what year your Mac is?

**Comment by VoidSequencx** [comment]
> I’m not a dev or anything but I’m just curious what year your Mac is

Oh yea, I just cleared my mac's cache and everything got fixed now lol
My device is a 14 inch mbp (2021)
