### ISSUE TITLE
Does Not Work On Roblox Version 0.566.0.5660545 (5660545) macOS Ventura 13.2.1 (16-Inch 2019 MacBook Pro) (Console Version Of FPS Unlocker)

### ISSUE THREAD

**Issue by TAM-Monke** [lanylow/rbxfpsunlocker-osx#194]
So I tried to use it and it was not functioning and i was still capped at 60fps. Ventura does allow games to go more than 60 fps on a 60 hertz display because I get 120fps on minecraft java edition. Please tell me what to do or if you can address this issue.

**Comment by lanylow** [comment]
Minecraft isn't Roblox, it doesn't have display sync enabled.

**Comment by TAM-Monke** [comment]
> Minecraft isn't Roblox, it doesn't have display sync enabled.

I know that but I still need to know what I can do to use the fps unlocker

**Comment by TAM-Monke** [comment]
One other thing to mention is that I know my machine is powerful enough because I bought a Intel i9, 16GB Of RAM, AMD Radeon 5500M, And 1TB SSD

**Comment by snoopchallenge** [comment]
https://github.com/lanylow/rbxfpsunlocker-osx/blob/main/README.md

**Comment by TAM-Monke** [comment]
> https://github.com/lanylow/rbxfpsunlocker-osx/blob/main/README.md

What is your point in putting that link

**Comment by TAM-Monke** [comment]
Why did you close it.

**Comment by TAM-Monke** [comment]
It’s not completed
