### ISSUE TITLE
Base process constructor failed

### ISSUE THREAD

**Issue by svtrn** [lanylow/rbxfpsunlocker-osx#195]
![Screenshot 2023-03-17 at 00 28 01](https://user-images.githubusercontent.com/127627896/225781334-820576e0-9eb9-4b01-9062-fabd7852a5ad.png)

keep getting this error im on mac os 10.15.7 followed all instructions on the vid is

**Comment by pierrelee12** [comment]
Same issue here.

However, I realised that on MAC OS Ventura it works, but on Monterey it does not. 

I hope the devs can comment something on this.

**Comment by pierrelee12** [comment]
I see. 

I do not recommend updating to Ventura anyway, as in Roblox, even if you have the FPS Unlocked, you will not get more than 60fps anyway.

**Comment by pierrelee12** [comment]
Still hope there's a solution for this though.

**Comment by lanylow** [comment]
Read new instructions on the [script branch](https://github.com/lanylow/rbxfpsunlocker-osx/tree/script).
