### ISSUE TITLE
zsh: no such file or directory: sudo/Users/userDownloads/rbxfpsunlocker_osx

### ISSUE THREAD

**Issue by jimmy12304** [lanylow/rbxfpsunlocker-osx#196]
it doesnt let me run it

**Comment by snoopchallenge** [comment]
use the file path where the fps unlocker is

**Comment by snoopchallenge** [comment]
sudo {filepath}

replace filepath with the file path

**Comment by jimmy12304** [comment]
it says command not found

**Comment by snoopchallenge** [comment]
make sure there is a space between sudo and the filepath and that the filepath leads to the fps unlocker

**Comment by jimmy12304** [comment]
it runs but idk if its working bc it wont show

**Comment by snoopchallenge** [comment]
check fps in roblox

**Comment by jimmy12304** [comment]
how?

**Comment by snoopchallenge** [comment]
play a roblox fps test game or join any game and show fps (idk how on macos but on windows it is shift+f5)

**Comment by snoopchallenge** [comment]
if it goes above 60fps it works
