### ISSUE TITLE
Console: exception: Couldn't get the main module

### ISSUE THREAD

**Issue by chowc13** [lanylow/rbxfpsunlocker-osx#198]
![Screenshot 2023-03-19 at 4 47 25 PM](https://user-images.githubusercontent.com/65959238/226163985-0eb0f8d3-dd2d-471f-a9ed-171b4172de8c.png)
Any idea what this is? my normal Roblox fps is at around 19 and I want it higher...

**Comment by lanylow** [comment]
This doesn't make your fps higher, it only removes the 60 fps limit. If you actually have 19 fps, your computer is way too weak to run roblox. That said, instructions on how to solve your issue are in the description of the latest release.
