### ISSUE TITLE
The unlocker is Interfering with something ( Mac os 10.15.7)

### ISSUE THREAD

**Issue by 0runz** [lanylow/rbxfpsunlocker-osx#199]
I mainly use the unlocker for da hood and macro and it was working fine until now where it is interfering with the macro for some reason. Never done that but now macro only work on 60 fps (default), if I change it to 120 the macro wont work, it feel like something is interfering with it and holding it back

**Comment by lanylow** [comment]
You should ask the developer of the macro.
