### ISSUE TITLE
Doesn't work at 10.15.0

### ISSUE THREAD

**Issue by VarrickST** [lanylow/rbxfpsunlocker-osx#20]
Why does it says "libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Failed to get Rloblox process info.
zsh: abort      sudo ./rbxfpsunlocker 144"
I did that correctly
(idk if i did that wrongly im just dumb ;-;)

update: i meant 10.15.5 also.i did the highsierra too but doesnt work as well
update #2: im dumb i didnt open riblos lmao

**Comment by lanylow** [comment]
Try downloading the [rbxfpsunlocker-highsierra.zip](https://github.com/lanylow/rbxfpsunlocker-osx/releases/download/v1.0.0/rbxfpsunlocker-highsierra.zip) release.
