### ISSUE TITLE
logic_error: Failed to get Roblox process info.

### ISSUE THREAD

**Issue by BL4K-H4CK3R** [lanylow/rbxfpsunlocker-osx#206]
for the past 4 to 5 hours, me and my friend I, despite our Roblox running for more than 2 hours as well as trying to launch Roblox through the terminal, it just said
`logic_error: Failed to get Roblox process info.`
`Make sure Roblox is open and try again.`
I don't know how to fix it please resolve my issue
![IMG_8019](https://user-images.githubusercontent.com/111638197/235782915-ae17c130-ae32-4dbb-85b0-72c381a875e0.jpeg)

**Comment by lanylow** [comment]
Read new instructions on the [script branch](https://github.com/lanylow/rbxfpsunlocker-osx/tree/script).
