### ISSUE TITLE
dyld: cannot load 'rbxfpsunlocker_osx 3'

### ISSUE THREAD

**Issue by Evvooooo** [lanylow/rbxfpsunlocker-osx#208]
Hello, I am on MacOS Sierra version 10.12.6

When i try to enter the command "sudo /Users/admin/Downloads/rbxfpsunlocker_osx 120-r", I get an error message :

"dyld: cannot load 'rbxfpsunlocker_osx 3' (load command 0x80000034 is unknown)
Abort trap: 6"

![Screen Shot 2023-05-23 at 03 27 17](https://github.com/lanylow/rbxfpsunlocker-osx/assets/114826898/88140c63-af81-4af4-bdd2-0df7e8fed118)

I also tried with an older version of the FPSunlocker, and get a different error message :

When i type "sudo /Users/admin/Downloads/rbxfpsunlocker 120 ", 
I get the following :

"dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/admin/Downloads/rbxfpsunlocker 2
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/admin/Downloads/rbxfpsunlocker 2
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6"

![Screen Shot 2023-05-23 at 03 33 37](https://github.com/lanylow/rbxfpsunlocker-osx/assets/114826898/0a0e8dc5-afb1-4188-9fee-cead53e9788f)

Thank you for reading and i hope you will be able to help me !

**Comment by lanylow** [comment]
Update your mac to at least macOS Catalina.
