### ISSUE TITLE
Why doesn't it uncap the fps on ventura

### ISSUE THREAD

**Issue by 3Percs4Zoid** [lanylow/rbxfpsunlocker-osx#210]
Im currently trying to find a way for the fps unlocker to uncap on ventura without monitor hz if any of the creators can tell me why I might be able to find a way.

**Comment by lanylow** [comment]
It's called vertical sync, you need to disable it and then you'll see the effect of this program.

**Comment by 3Percs4Zoid** [comment]
> It's called vertical sync, you need to disable it and then you'll see the effect of this program.

I did disable vertical sync with xcode and it still doesn't work only caps my fps to my monitors hz

**Comment by lanylow** [comment]
If you're talking about Quartz Debug, it doesn't seem work on ventura. You can force Roblox to use OpenGL which has vertical sync disabled by default, that's verified to work by me and many other people from the discord server.

**Comment by 3Percs4Zoid** [comment]
>

> If you're talking about Quartz Debug, it doesn't seem work on ventura. You can force Roblox to use OpenGL which has vertical sync disabled by default, that's verified to work by me and many other people from the discord server.

How do I exactly force to to use OpenGL?
