### ISSUE TITLE
Update for Roblox Byfron Anticheat update.

### ISSUE THREAD

**Issue by jeremylpro** [lanylow/rbxfpsunlocker-osx#212]
Read the title.

**Comment by minhpicasa** [comment]
So it's working fine but you need a monitor/macbook pro that have a refresh rate higher than 60hz and the limit is only able to meet that refresh rate (eg: I have a 75hz monitor the limit is only 75 fps and not able to set any higher)

**Comment by lanylow** [comment]
> So it's working fine but you need a monitor/macbook pro that have a refresh rate higher than 60hz and the limit is only able to meet that refresh rate (eg: I have a 75hz monitor the limit is only 75 fps and not able to set any higher) 

Yes that's the case on macOS Ventura.

Answering the original question, I have no clue what you're talking about. There is no anti-cheat on macOS yet, Byfron is only in the Windows version.

**Comment by undyuuang** [comment]
> > So it's working fine but you need a monitor/macbook pro that have a refresh rate higher than 60hz and the limit is only able to meet that refresh rate (eg: I have a 75hz monitor the limit is only 75 fps and not able to set any higher)
> 
> Yes that's the case on macOS Ventura.
> 
> Answering the original question, I have no clue what you're talking about. There is no anti-cheat on macOS yet, Byfron is only in the Windows version.

Hydrogen says they needed update for the anticheat and only worked after update so I guess there is a anti cheat

**Comment by gostgamer6166** [comment]
is there anyway to bypass the ventura cap or should I just downgrade to monterey ??
I have been trying to get an fps unlocker for ages because the game I play is basicly 70% fps 20% ping 10% skill....
