### ISSUE TITLE
Issue on MacOS Sonoma, and general issue 

### ISSUE THREAD

**Issue by NoahCxrest** [lanylow/rbxfpsunlocker-osx#215]
When I launch ROBLOX without the FPS unlocker, it works fine. However, when I run it with the FPS unlocker - ROBLOX doesn't run anymore. I can't open the app - it just says "Unable to open ROBLOX", I assume this is an issue with the anticheat? I can provide further details if needed.

**Comment by lanylow** [comment]
This is probably because you have an M1 or M2 mac. Related to #214.
