### ISSUE TITLE
Corrupts my roblox installation

### ISSUE THREAD

**Issue by muniscool** [lanylow/rbxfpsunlocker-osx#217]
When I use it, the base constructor error appears, but when I use the -r command, it works with no error, but corrupts my roblox installation. After I use it, Finder just says it can't be opened. Why I think it corrupts it? Cause when I reinstall roblox, it launches again. My macOS version is 12.6.4 Monterey. It doesn't break my Studio installation, but I think that is just due to the fact that I don't use the -s command. I see that this has a lot of similarities with the other issue about the fact that it has no error, but doesn't unlock. For me it did that before, and now it is doing this. Also while it does this, it puts up no error, just like that issue. First it worked for me, then the base constructor error started appearing (this is when it stopped working entirely) I put up the -r command, and it does nothing except this time it doesn't put up any error. And finally this issue. Any possible fixes?

**Comment by lanylow** [comment]
Please read #214.
