### ISSUE TITLE
Doesn't change fps nor throw error (M1 Silicon chip)

### ISSUE THREAD

**Issue by overdramaticpanromantic** [lanylow/rbxfpsunlocker-osx#218]
I run the command that is listed and no error is thrown. Tried restarting my PC, restarting Roblox, etc. Despite this, FPS does not change, instead remaining at 60. I can run games much more resource-intensive than Roblox at significantly higher FPS than 60, e.g. modded Mindustry at 720 FPS.
<img width="1123" alt="image" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/108166075/797fac6c-f7c8-44de-8792-79b60ec0dc59">

**Comment by lanylow** [comment]
Read additional notes on the latest release.
