### ISSUE TITLE
Abort Trap 6:

### ISSUE THREAD

**Issue by GarrettGee63** [lanylow/rbxfpsunlocker-osx#221]
This is what I gotback after running it--->

macOS Roblox FPS Unlocker
Currently in-development, use at your own risk.
Created by lanylow and Seizure Salad.
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/garrettgee/Downloads/FPSUNLOCKER/rbxfpsunlocker
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/garrettgee/Downloads/FPSUNLOCKER/rbxfpsunlocker
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by lanylow** [comment]
Update your mac to at least macOS Catalina.
