### ISSUE TITLE
logic_error: Couldn't find the task scheduler pattern.

### ISSUE THREAD

**Issue by Henzone** [lanylow/rbxfpsunlocker-osx#222]
logic_error: Couldn't find the task scheduler pattern.
Roblox updates can cause this.
Check the GitHub for any new updates.
![Screenshot 2023-08-11 at 1 39 02 PM](https://github.com/lanylow/rbxfpsunlocker-osx/assets/55535670/df4583cc-aa7f-4bda-907d-af0e271e976d)

**Comment by lanylow** [comment]
#214
