### ISSUE TITLE
when i follow everything it still gives me this see foto

### ISSUE THREAD

**Issue by F1nnL** [lanylow/rbxfpsunlocker-osx#224]
<img width="494" alt="Screenshot 2023-08-21 at 12 38 34" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/142795746/c62cd2fe-f071-43d1-ac81-5dadf21cf3ef">

**Comment by F1nnL** [comment]
plus it corrupted my Roblox instal

**Comment by lanylow** [comment]
Read #214.

**Comment by F1nnL** [comment]
but i am using an intel build tho?

**Comment by lanylow** [comment]
Are you sure you're running the command ending with `-r` when Roblox is closed?

**Comment by F1nnL** [comment]
Yes I’m very sure, I tried again and got the same results

**Comment by lanylow** [comment]
Read new instructions on the [script branch](https://github.com/lanylow/rbxfpsunlocker-osx/tree/script).
