### ISSUE TITLE
logic_error: Couldn't find the task scheduler pattern.

### ISSUE THREAD

**Issue by Juicedu** [lanylow/rbxfpsunlocker-osx#225]
Yesterday (August 22) the Roblox FPS unlocker was working just fine until today. I have tried using the sudo /Users/MyUser/Downloads/rbxfpsunlocker_osx 0 -r command to try to resort this problem but when I get input the sudo /Users/MyUser/Downloads/rbxfpsunlocker_osx 144 command I get an error that says it couldn't find the task scheduler pattern.  
<img width="696" alt="Screen Shot 2023-08-23 at 1 24 25 PM" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/143026584/ca11777a-9522-47f7-8136-0c07530faadd">

**Comment by skiesfr** [comment]
Lol me too they need to fix this is because of the new roblox update it broke the fps unclocker but they dont update a while the unclocker so we might need to wait a bit

**Comment by lanylow** [comment]
Fixed in the latest release.
