### ISSUE TITLE
exception: Couldn't find the task scheduler signature.

### ISSUE THREAD

**Issue by Zalryn** [lanylow/rbxfpsunlocker-osx#226]
after doing all the sudo cmds. 
- re installing roblox
- re installing the fps unlocker

still after typing these cmds down
sudo /Users/MyUser/Downloads/rbxfpsunlocker_osx 0 -r
sudo /Users/MyUser/Downloads/rbxfpsunlocker_osx 0

![Screenshot 2023-08-23 at 22 01 44](https://github.com/lanylow/rbxfpsunlocker-osx/assets/143036649/210c5fba-6a6f-4ca7-8281-212af31792ed)

**Comment by Zalryn** [comment]
please solve as soon as possible.

**Comment by lanylow** [comment]
Read #214.

**Comment by Zalryn** [comment]
> 

what should I do?

**Comment by Zalryn** [comment]
> Read #214.

could you make one?

**Comment by Zalryn** [comment]
> Read #214.

well, could you find a different way changing to the source code?

**Comment by Zalryn** [comment]
please i really need this unlocker.
