### ISSUE TITLE
New roblox update made roblox not launch after running fps unlocker -r

### ISSUE THREAD

**Issue by probabalyJackie** [lanylow/rbxfpsunlocker-osx#227]
https://github.com/lanylow/rbxfpsunlocker-osx/assets/117324349/791b7fc6-4813-4ad5-8dd1-35fded26ed40

**Comment by lanylow** [comment]
Read #214.

**Comment by probabalyJackie** [comment]
> Read #214.

dang I have to disable System Integrity Protection to play roblox

**Comment by probabalyJackie** [comment]
I figured out how to unlock fps, read this https://devforum.roblox.com/t/how-to-unlock-the-60-fps-cap-withwithout-software/2220352

**Comment by probabalyJackie** [comment]
you can automate by running


rsync -av /Users/youruser/Downloads/ClientSettings  /Applications/Roblox.app/Contents/MacOS
