### ISSUE TITLE
Can't find task scheduler signature (Intel Mac, running Monterey 12.6.6)

### ISSUE THREAD

**Issue by kalberet** [lanylow/rbxfpsunlocker-osx#228]
**Yes, I am 100% on an Intel Mac**
The error I am running into is
exception: Couldn't find the task scheduler signature

I'm not sure whether this has something to do with a roblox update or whatnot.

**Comment by kalberet** [comment]
Sorry for the unclear title. Fixed it

**Comment by lanylow** [comment]
Hello, this issue has been reported to me by other users as well. I'm not sure why but it works just fine for me, so I assume I'm on a different update channel and my Roblox version isn't the same as yours. That means you will probably have to wait until I'm on the same version so I can fix it.

**Comment by lanylow** [comment]
Fixed in the latest release.
