### ISSUE TITLE
when ever i open roblox it gives me the error "roblox cannot be opened" and as soon as i uninstall the fps unlocker it works

### ISSUE THREAD

**Issue by uiezxx** [lanylow/rbxfpsunlocker-osx#231]
i can screenshare and show a recording of this issue but ive tried everythiung

**Comment by ghost** [comment]
same Can you please fix this.

**Comment by lanylow** [comment]
Read new instructions on the [script branch](https://github.com/lanylow/rbxfpsunlocker-osx/tree/script).
