### ISSUE TITLE
The -r command does not work and breakes roblox (Doesnt let me open roblox)

### ISSUE THREAD

**Issue by sajstar** [lanylow/rbxfpsunlocker-osx#234]

**Comment by sajstar** [comment]
<img width="1915" alt="image" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/143147347/20013706-abfb-42f0-9a53-59fb9b65c799">
<img width="1914" alt="image" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/143147347/4d1e6420-4a50-425d-b74e-1a3944765eb9">

**Comment by SparkysServant** [comment]
Same thing happening to me too, never had a problem with it until yesterday. I have a M1 Mac, i dont get why it wouldnt wanna work with the M1's anymore. I have the latest model

**Comment by uiezxx** [comment]
same with me

**Comment by gunnajsu** [comment]
same they need to fix this asap its so bad to play on 60

**Comment by sajstar** [comment]
Please fix this I don't wanna keep playing on 60 fps.

**Comment by sajstar** [comment]
<img width="572" alt="image" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/143147347/1b62b186-0f9e-4c14-92e1-779e304d84ed">

**Comment by ghost** [comment]
Same though

**Comment by lanylow** [comment]
Read new instructions on the [script branch](https://github.com/lanylow/rbxfpsunlocker-osx/tree/script).
