### ISSUE TITLE
Breaks Roblox

### ISSUE THREAD

**Issue by SparkysServant** [lanylow/rbxfpsunlocker-osx#235]
The program breaks roblox once i enter the pathname on the terminal and doesnt allow me to open roblox. Once I redownload roblox and delete the unlocker, roblox functions normally but of course without the fps unlocker. Glad im not the only one having this issue. Please help fix this

**Comment by ghost** [comment]
Same whenever I do it correctly it breaks roblox and I can't get back in but I have fund a process to get back into roblox but please fix this issue its the only issue I am having Lanylow thank you.

**Comment by lanylow** [comment]
Read new instructions on the [script branch](https://github.com/lanylow/rbxfpsunlocker-osx/tree/script).
