### ISSUE TITLE
Roblox is not able to run when the terminal has completed the installation.

### ISSUE THREAD

**Issue by Syfriea** [lanylow/rbxfpsunlocker-osx#237]
(_Seems like this apply for all versions_)

**Severity** - High
**Location** - Roblox/RBXFPSUNLOCKER-OSX
**Issue** - "When the FPS Unlocker has been fully installed to -r (or Roblox) it seems like it will make Roblox not able to run and gives me a error saying that Roblox isn't able to open" 
**Version** - 2.0.2 (And all of the other versions)
**OS** - 11.7.9 (Doesn't work for Monterey too)
**Logs and etc** - N/A

**Comment by lanylow** [comment]
Read the new [README](https://github.com/lanylow/rbxfpsunlocker-osx/blob/script/README.md). The version you're using is outdated.

**Comment by Syfriea** [comment]
Gotcha.

**Comment by Eggsboy77** [comment]
Very goood
