### ISSUE TITLE
Rbxfpsunlocker-osx high sierra version isnt working

### ISSUE THREAD

**Issue by 0Knox** [lanylow/rbxfpsunlocker-osx#24]
So i loaded up the terminal code. then i made a new window. i typed in cd downloads i pasted the command while roblox was running in the backgrownd. then it said that my fps was capped to 144fps then when i went to check how much fps i have it said i still have 29fps. so i decided to turn off Vsync then i did the steps again. but it still said i have 29 fps. please fix the problem.           

Thanks!

**Comment by lanylow** [comment]
This program won't boost your FPS, it removes the 60 FPS cap that is enabled by default in Roblox. In short: if your game is normally running at 29 FPS, it won't get any higher than that.
