### ISSUE TITLE
The command cannot be found

### ISSUE THREAD

**Issue by Jame-s-wift** [lanylow/rbxfpsunlocker-osx#242]
The command cannot be found and when i used the file name to run the command, it says

exception: base_process constructor failed.

thats the error i get

**Comment by Harry205** [comment]
mee tooo

**Comment by Jame-s-wift** [comment]
Im not sure weather its because of venture but I do have a pro with 120Hz

**Comment by lanylow** [comment]
Before I close this, let me ask you, what instructions exactly did you follow? They sure aren't what's currently in this repository.
