### ISSUE TITLE
exception: base_process constructor failed.

### ISSUE THREAD

**Issue by Zac08** [lanylow/rbxfpsunlocker-osx#243]
I'm on macOS Sonoma at the moment (with a MacBook M2 pro), and the same error keeps occurring. exception: base_process constructor failed. I've tried the previous methods of using '-r' at the end which helps clear the exception, but the script does not not work (Roblox FPS limit is not overwritten and '60FPS, does not change to '120FPS). I have tried the process many times, and is not working. I am sorry if I have over-looked any recommendations, but can you please help?

<img width="306" alt="Screenshot 2023-09-19 at 8 58 48 PM" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/145438617/9bd4fd4f-6755-41ff-9671-1a94d83279dd">

**Comment by lanylow** [comment]
Go to the main page of this repository and read the instructions.
