### ISSUE TITLE
dont show

### ISSUE THREAD

**Issue by PhapNoSy** [lanylow/rbxfpsunlocker-osx#245]

**Comment by PhapNoSy** [comment]
<img width="727" alt="Ảnh chụp Màn hình 2023-09-21 lúc 18 18 58" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/118717791/1179a2fe-a6c2-4275-9d30-8e5140e2c7a6">
<img width="727" alt="Ảnh chụp Màn hình 2023-09-21 lúc 18 19 32" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/118717791/ab55abf6-7c2f-474a-9f42-bcf0129cf00b">

**Comment by lanylow** [comment]
I don't understand what your issue is.

**Comment by PhapNoSy** [comment]
> I don't understand what your issue is.

uhhh i press f5, cmd f5, shift f5 more button with f5 but it dont show fps

**Comment by lanylow** [comment]
Try fn + shift + f5.

**Comment by PhapNoSy** [comment]
> Try fn + shift + f5.

k
