### ISSUE TITLE
FPS fluctuates from 120 fps to 80 fps

### ISSUE THREAD

**Issue by FlamingVelocity** [lanylow/rbxfpsunlocker-osx#255]
Hello.

I literally made this account just for this, I am also no coder or programmer myself, so I have no idea what I'm talking about probably.

Every time my launcher is open (essentially, in game), my fps will fluctuate from 120 to 80 fps. It just makes the screen look so much more choppy when at 80 fps compared to 120 (I want to keep my fps at 120).

Any fixes? or just more of Apple's jank I need to deal with with no solutions.

**Comment by lanylow** [comment]
Sounds like your mac is just too weak to keep up with rendering 120 fps.

**Comment by FlamingVelocity** [comment]
Is that really all there is to it? Nothing else you can think of?

I have an M1 Mac, is it still ‘too weak’ or is there anything else I can do to try and keep my fps at 120?

**Comment by Juicedu** [comment]
Keep in mind its a Mac, Macs are known for more desktop work/photography. If your playing a really high demand game on roblox expect it not to be 120. 120 is the CAP point of it from 0-120. Again what lanylow said, it might be your Mac. I have a 2013 Mac that runs just fine at 120. Yes it is not going to always stay at 120, it will try its best. Unless you have any saved money to spend, you will just have to live with it.
