### ISSUE TITLE
Aspect Ratio and Zoom all broken after Roblox update on November 30th

### ISSUE THREAD

**Issue by rithkott** [lanylow/rbxfpsunlocker-osx#262]
Installing the fps unlocked makes the Roblox app appear zoomed in and the button positions are all wrong, as if its displayed in the wrong resolution

**Comment by Elijahb04** [comment]
I'm experiencing the same problem.

**Comment by CheekyCodes** [comment]
can replicate

**Comment by hello2340** [comment]
same issues

**Comment by Ritish-Mithiradas** [comment]
same issue

**Comment by tjw1245** [comment]
same thing here

**Comment by tjw1245** [comment]
@lanylow please help us fix this

**Comment by Juicedu** [comment]
Hi I've noticed a lot of display issues, can anyone provide me a screenshot because I am all fine here running 120 FPS and regular display. If your curious I have a late 2015 iMac Retina, would like to know if you guys have older models (likely not the case of issue).

**Comment by tjw1245** [comment]
Its for 2nd displays

**Comment by lanylow** [comment]
Duplicate of #256.
