### ISSUE TITLE
Off Centered Screen When FPS Unlocker Is Being Used On Macbook

### ISSUE THREAD

**Issue by tjw1245** [lanylow/rbxfpsunlocker-osx#264]
When using fps unlocker on Macbook with a 2nd display its off centered and really zoomed in and wont click on what your cursor is on. Someone please answer this already. 
<img width="1336" alt="Untitled" src="https://github.com/lanylow/rbxfpsunlocker-osx/assets/152564491/c0acad2e-a079-44d9-ab9c-c920f5e43750">

**Comment by Ritish-Mithiradas** [comment]
same issue here

**Comment by hello2340** [comment]
@lanylow i still got this issue

**Comment by lanylow** [comment]
Duplicate of #256.
