### ISSUE TITLE
Allow running without root access

### ISSUE THREAD

**Issue by Thyssenkrupp234** [lanylow/rbxfpsunlocker-osx#27]
Hi, I'm new to C++ so tell me if this isn't possible.

Currently, the tool requires sudo privileges, but couldn't it be possible to not require root privileges for the per-user installed roblox? Since you are only editing the `$HOME/Applications/Roblox.app` and not the /Applications/Roblox.app, it shouldn't require sudo, if I am correct.

Please tell me if this isn't possible, but if it is it would be a nice addon.

**Comment by lanylow** [comment]
The reason for that is because it reads and writes memory of an external process (that is Roblox), which requires elevated privileges simply because the operating system wouldn’t allow an unprivileged program to do that. It doesn't edit the app, it edits the memory allocated by it.

**Comment by Sushi8537** [comment]
Hi Lany. Does the fps unlocked work full screen? when I enter it it goes back to 60 fps
