### ISSUE TITLE
Fps cap

### ISSUE THREAD

**Issue by StarEren** [lanylow/rbxfpsunlocker-osx#28]
It caps fps at 120 if I set it to anything higher than 120. For example terminal says the fps is capped at 300 but Roblox shows 120. I've even tried compiling then executing the command.

**Comment by StarEren** [comment]
it used to work before until I deleted and downloaded it again, so the problem could be a change done

**Comment by SeizureSaladd** [comment]
> It caps fps at 120 if I set it to anything higher than 120. For example terminal says the fps is capped at 300 but Roblox shows 120. I've even tried compiling then executing the command.
We know this is a problem and honestly have no idea why it happens
