### ISSUE TITLE
cd in Terminal

### ISSUE THREAD

**Issue by FIRMz** [lanylow/rbxfpsunlocker-osx#29]
I put cd and the information under where and press enter and it doesn't do anything.

**Comment by SeizureSaladd** [comment]
Using the `cd` command won't return anything in the terminal window but will put your terminal in that folder so you can run the command to run the FPS unlocker

**Comment by FIRMz** [comment]
I get what you mean

**Comment by FIRMz** [comment]
Nevermind I just got it to work. Thanks for making this.
