### ISSUE TITLE
Terminal Command Not Working

### ISSUE THREAD

**Issue by Signupgary** [lanylow/rbxfpsunlocker-osx#31]
After using this FPS unlocker for quite a while, an error suddenly occurred. After I paste (sudo ./rbxfpsunlocker 120) in the downloads folder from Terminal, an error occurred. This suddenly started happening this morning and I'm not sure if it's because Roblox updated and messed with the settings. 

Image of issue: https://user-images.githubusercontent.com/97556778/158692713-8c2d6a02-6c0e-4ef5-a097-52137d438536.png

**Comment by SeizureSaladd** [comment]
Thanks for this. We'll make sure to update asap.

**Comment by lanylow** [comment]
Yeah, that's because of the update. I'll update when I have time.

**Comment by StarEren** [comment]
If you can, please fix the issue where it can't go over 120 as well

**Comment by russiakick3000** [comment]
I hate to be that guy but is there any estimation on when this will be updated?

**Comment by SeizureSaladd** [comment]
> If you can, please fix the issue where it can't go over 120 as well

We honestly have no idea why it does this lol

**Comment by zaidzdz** [comment]
do you know when it will upadate now?

**Comment by lanylow** [comment]
It's going to be fixed whenever seizure has time to test my code, because I don't own a mac and can't check it myself. I'm leaving this issue opened only so other people with the same question can see this message, so **please don't respond here**. If you want to propose testing for me - sorry, but no, you just have to wait.

**Comment by sanctions823** [comment]
> If you can, please fix the issue where it can't go over 120 as well

This isn't something they can fix however there is a way to get more than 120 fps you gotta disable the vertical sync there's a video on how to disable it made by nihilize https://www.youtube.com/watch?v=xsjIJwobrfw

**Comment by SeizureSaladd** [comment]
the issue has been resolved check new releases everybody
