### ISSUE TITLE
Still is not working.

### ISSUE THREAD

**Issue by zaidzdz** [lanylow/rbxfpsunlocker-osx#34]
Your page says that it fixed the schedular pattern not found bug, but when I downoladed it and did all the steps again it still has the bug.
![Screen Shot 2022-03-18 at 6 35 26 PM](https://user-images.githubusercontent.com/81050752/159093241-266881c1-d633-4d16-a701-e607b36bf26a.png)

**Comment by lanylow** [comment]
I can tell this is not the latest version because of unhandled exceptions. Make sure you're downloading the v1.0.1 release.

**Comment by zaidzdz** [comment]
I downloaded the latest verison agian and it still dosent work.

**Comment by Somedude72** [comment]
not working for me either. Downloaded and redownloaded

**Comment by SeizureSaladd** [comment]
> I downloaded the latest verison agian and it still dosent work.

Make sure you don't have two of the same file names and you also have a new terminal instance in the folder with new file in it

**Comment by zaidzdz** [comment]
What do you mean by having a new terminal instance in the folder with a mew file in it?

**Comment by Somedude72** [comment]
Nevermind it works now

**Comment by zaidzdz** [comment]
How?

**Comment by SeizureSaladd** [comment]
> What do you mean by having a new terminal instance in the folder with a mew file in it?

I mean like don't have the terminal in your like desktop folder when the file is in your downloads

**Comment by zaidzdz** [comment]
The terminal is in downloads, do I have to put it in the fps unlocker folder, if so how do I do it?

**Comment by lanylow** [comment]
Just delete all versions you currently have and download the latest one again.

**Comment by zaidzdz** [comment]
It works now. Thank you so much for your help and time. Have a good day!
