### ISSUE TITLE
Fps Unlocker not working for High Sierra

### ISSUE THREAD

**Issue by Endless69420** [lanylow/rbxfpsunlocker-osx#35]
Hello,
I tried to download the newest version because the old one wasn't working due to Roblox updates. It gave me an error message saying its only working for Mac OS X 12.0 or higher. There isn't any high sierra option like the previous update and I just tried to push my luck to see if it would work. Are you going to add an update that works for High Sierra - If so, it would mean a lot to me. Thank you for your time.

**Comment by lanylow** [comment]
You have to compile it yourself.

**Comment by Endless69420** [comment]
Alright thank you

**Comment by lanylow** [comment]
If you manage to compile it, could you send the binary here so I can post it in the release?

**Comment by Endless69420** [comment]
No sorry, I wasn't successful in doing so.
