### ISSUE TITLE
application has to be ran as root

### ISSUE THREAD

**Issue by AntonIsFilipinoYeahThatsIsRight** [lanylow/rbxfpsunlocker-osx#36]
runtime_error: This application has to be ran as root.
Usage: sudo ./rbxfpsunlocker <cap> this is what the red text says @lanylow

**Comment by AntonIsFilipinoYeahThatsIsRight** [comment]
ok imma play tds now

**Comment by lanylow** [comment]
Run it with sudo.

**Comment by AntonIsFilipinoYeahThatsIsRight** [comment]
> Run it with sudo.

and how do i do that i am 8 that uses a mac

**Comment by AntonIsFilipinoYeahThatsIsRight** [comment]
i just use windows im not used to mac

**Comment by lanylow** [comment]
Exact instructions are written in the readme, you open a terminal and run the command from there.

**Comment by AntonIsFilipinoYeahThatsIsRight** [comment]
it just says that i run it and says that cannot do anything anymore

**Comment by AntonIsFilipinoYeahThatsIsRight** [comment]
<img width="423" alt="Screen Shot 2022-03-23 at 12 44 12 PM" src="https://user-images.githubusercontent.com/88090255/159721751-682fdae4-fdd9-4124-a9af-6bb0bbc80aa3.png">

**Comment by lanylow** [comment]
I wonder why.

**Comment by AntonIsFilipinoYeahThatsIsRight** [comment]
is there an answer.

**Comment by lanylow** [comment]
Try following what's in the readme, I heard it works.

**Comment by zaidzdz** [comment]
Maybe try delteing and downloading the file agian.

**Comment by AntonIsFilipinoYeahThatsIsRight** [comment]
redownloaded it and still is saying it

**Comment by SeizureSaladd** [comment]
> redownloaded it and still is saying it
> 
> 

You have to add `sudo` in front of the command

**Comment by celakeniock** [comment]
cd <direction wheres fpsunlocker>
sudo ./rbxfpsunlocker 144

it should work

**Comment by ItsMeUngasis** [comment]
Once you download the file, go to the finder and then double click the rbxfpsunlocker.zip file to extract then right click the rbxfpsunlocker (without the .zip) and click the "Open with" and select "Terminal" after the rbxfpsunlocker terminal appear, right click the terminal (in the dock) and click the "New Window", a new terminal will appear and then write "cd <file where rbxfpsunlocker is>" and then the new terminal will be renamed to what file name you entered and then write "sudo ./rbxfpsunlocker 120" and it will ask your password (password of the account you currently using), just enter the password and it should work fine (make sure your in game before you change your fps)

**Comment by AntonIsFilipinoYeahThatsIsRight** [comment]
thank you

**Comment by AntonIsFilipinoYeahThatsIsRight** [comment]
command not found says
oof

**Comment by AntonIsFilipinoYeahThatsIsRight** [comment]
ok nvm sorry did not undertsand what you said

**Comment by ItsMeUngasis** [comment]
> ok nvm sorry did not undertsand what you said

does it work?

**Comment by ItsMeUngasis** [comment]
watch this if you still dont get it (https://www.youtube.com/watch?v=R80OHA-LiPE)
