### ISSUE TITLE
Roblox update did an ERROR to the app new version needs to be added

### ISSUE THREAD

**Issue by insanityplays** [lanylow/rbxfpsunlocker-osx#37]
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: This application has to be ran as root.
macOS Roblox FPS Unlocker
Currently in-development, use at your own risk.
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Couldn't find the task scheduler pattern.
Roblox updates can cause this.
Check the GitHub for any new updates.
Created by lanylow and Seizure Salad.Abort trap: 6

**Comment by lanylow** [comment]
Download the latest release.
