### ISSUE TITLE
For some reason when I select my desired fps cap it always go's to 120

### ISSUE THREAD

**Issue by zaidzdz** [lanylow/rbxfpsunlocker-osx#38]

**Comment by lanylow** [comment]
This is caused by V-Sync enforced by macOS, I heard there is a tool that allows you to disable it but I don't know how it's called.

**Comment by zaidzdz** [comment]
But then why did the unlocker work with 165 before?

**Comment by zaidzdz** [comment]
Is it like mac updated it

**Comment by zaidzdz** [comment]
nvm It works now.
