### ISSUE TITLE
Binary built for Monterey only

### ISSUE THREAD

**Issue by Thyssenkrupp234** [lanylow/rbxfpsunlocker-osx#39]
With the latest release, the binary is built for macOS 12.0 and up. This results with the following error message on Big Sur and older (Currently on High Sierra):

`macOS Roblox FPS Unlocker
Currently in-development, use at your own risk.
Created by lanylow and Seizure Salad.
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/lincolnmuller/./rbxfpsunlocker (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/lincolnmuller/./rbxfpsunlocker (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libSystem.B.dylib

fish: Job 1, 'sudo ./rbxfpsunlocker 300' terminated by signal SIGABRT (Abort)`

Of course, this could be fixed by recompiling on an older OS, such as High Sierra, or Mojave. 

Also, [MacStadium](https://www.macstadium.com/) provides free Mac's to build apps, I recommend you apply for a Mojave or High Sierra based mac mini or something, and then have a GitHub actions recompile the binary.

Cheers

**Comment by lanylow** [comment]
I'll take a look into that MacStadium thing, for now you have to compile it yourself (you can send me the binary here then).

**Comment by Thyssenkrupp234** [comment]
@lanylow
[rbxfpsunlocker.zip](https://github.com/lanylow/rbxfpsunlocker-osx/files/8356332/rbxfpsunlocker.zip)
 
if you plan to create a new release, just send me an email or something and I'd be happy to compile for you.

**Comment by lanylow** [comment]
Thanks.
