### ISSUE TITLE
FPS drops and locks from 120 to 80fps

### ISSUE THREAD

**Issue by Reydanny6** [lanylow/rbxfpsunlocker-osx#40]
Once I start the fps unlocker onto a roblox game, it'll lock onto 120 fps. but after some minutes my fps will just drop to 80 and lock onto that fps. only solution i had was to restart the whole fps command prompt session all over. But the exact same problem will happen again.

**Comment by SeizureSaladd** [comment]
This isn't a fps booster and the 120 fps issue is known and we're working on a fix

**Comment by Reydanny6** [comment]
> This isn't a fps booster and the 120 fps issue is known and we're working on a fix

my apologies, i meant fps unlocker.

**Comment by SeizureSaladd** [comment]
> > This isn't a fps booster and the 120 fps issue is known and we're working on a fix
> 
> 
> 
> my apologies, i meant fps unlocker. but this issue just currently started happening lately. Before this problem occured, my fps would lock onto 120 fps for hours, now it'll just go down and lock onto 80 fps in like 10-20 minutes

Honestly I have no idea why this is happening

**Comment by Reydanny6** [comment]
> > > This isn't a fps booster and the 120 fps issue is known and we're working on a fix
> > 
> > 
> > my apologies, i meant fps unlocker. but this issue just currently started happening lately. Before this problem occured, my fps would lock onto 120 fps for hours, now it'll just go down and lock onto 80 fps in like 10-20 minutes
> 
> Honestly I have no idea why this is happening

it's very confusing, especially since i'm using the MacBook Pro M1 Chip.

**Comment by SeizureSaladd** [comment]
> > > > This isn't a fps booster and the 120 fps issue is known and we're working on a fix
> 
> > > 
> 
> > > 
> 
> > > my apologies, i meant fps unlocker. but this issue just currently started happening lately. Before this problem occured, my fps would lock onto 120 fps for hours, now it'll just go down and lock onto 80 fps in like 10-20 minutes
> 
> > 
> 
> > Honestly I have no idea why this is happening
> 
> 
> 
> it's very confusing, especially since i'm using the MacBook Pro M1 Chip.

Hmm I'll take note of this

**Comment by Deezsen** [comment]
> > > > This isn't a fps booster and the 120 fps issue is known and we're working on a fix
> > > 
> > > 
> > > my apologies, i meant fps unlocker. but this issue just currently started happening lately. Before this problem occured, my fps would lock onto 120 fps for hours, now it'll just go down and lock onto 80 fps in like 10-20 minutes
> > 
> > 
> > Honestly I have no idea why this is happening
> 
> it's very confusing, especially since i'm using the MacBook Pro M1 Chip.

Something similar has happened to me, as it would lock on to 90 fps. i suggest restarting your computer or reinstalling the unlocker, both worker for me. (i'm using intel iMac so it may not work for you)

**Comment by Reydanny6** [comment]
> > > > > This isn't a fps booster and the 120 fps issue is known and we're working on a fix
> > > > 
> > > > 
> > > > my apologies, i meant fps unlocker. but this issue just currently started happening lately. Before this problem occured, my fps would lock onto 120 fps for hours, now it'll just go down and lock onto 80 fps in like 10-20 minutes
> > > 
> > > 
> > > Honestly I have no idea why this is happening
> > 
> > 
> > it's very confusing, especially since i'm using the MacBook Pro M1 Chip.
> 
> Something similar has happened to me, as it would lock on to 90 fps. i suggest restarting your computer or reinstalling the unlocker, both worker for me. (i'm using intel iMac so it may not work for you)

yeah i've done those solutions, some reason it just goes back to it. But i think i found a solution to it. Ever since I updated my MacBook, it started having a stable 120 fps and locked onto it. Problem never occured again.
