### ISSUE TITLE
FPS unlocker doesn't work

### ISSUE THREAD

**Issue by Thyssenkrupp234** [lanylow/rbxfpsunlocker-osx#41]
Is the project abandoned? Currently, the unlocker is broken and has been for the past 2-3 weeks.

**Comment by lanylow** [comment]
I've literally talked to a person who used it yesterday, are you sure you have the latest release?

**Comment by Thyssenkrupp234** [comment]
@lanylow 

Every time I have completely rebuilt it from source for maximum compatibility, I’ll try again

**Comment by SeizureSaladd** [comment]
> @lanylow 
> 
> 
> 
> Every time I have completely rebuilt it from source for maximum compatibility, I’ll try again

What does it say lol

**Comment by Thyssenkrupp234** [comment]
@SeizureSaladd, Currently rebuilding from source on High Sierra

**Comment by Thyssenkrupp234** [comment]
Works, had to disable fullscreen
