### ISSUE TITLE
FPS Caps at 120 even if set higher. (M1)(Monterey

### ISSUE THREAD

**Issue by CodeFloof** [lanylow/rbxfpsunlocker-osx#42]

**Comment by CodeFloof** [comment]
I have downloaded the latest version available, and I did notice that in a fps testing place, it does go higher than 120, although gameplay is still at 120 as well as physics. Any plans to fix this?

**Comment by SeizureSaladd** [comment]
known issue we have plans to fix it in future it's bc of vsync if you download quartz debug then you can disable it

**Comment by lanylow** [comment]
It’s not a bug, macOS is causing it, I checked and it's not our fault in any way. You’d have to use a tool like quartz debug to disable V-Sync.

**Comment by CodeFloof** [comment]
I'm not really good at coding is there a tutorial you can link?

**Comment by lanylow** [comment]
https://www.youtube.com/watch?v=xsjIJwobrfw

**Comment by Jannatul89sInGithub** [comment]
#69
