### ISSUE TITLE
"sudo: ./rbxfpsunlocker: command not found" - Catalina Intel cpu

### ISSUE THREAD

**Issue by seppata** [lanylow/rbxfpsunlocker-osx#44]
i've been using this for awhile, and its worked overall really well. untill recently when i launch roblox and try to enable it, a message saying the command isn't found is shown. i'm unsure i'm doing something wrong

**Comment by SeizureSaladd** [comment]
You have to use the `cd` command to enter the folder wherever the file is located and then you do the `sudo` command

**Comment by seppata** [comment]
i feel like such an idiot oh my god
