### ISSUE TITLE
Capped fps

### ISSUE THREAD

**Issue by wlumee** [lanylow/rbxfpsunlocker-osx#46]
I have a bug that my fps is capped at 240 or 96 when I unlock my fps.  
<img width="549" alt="image" src="https://user-images.githubusercontent.com/108336227/176156714-7456a417-f8af-4908-a812-2458ea8160fc.png">

**Comment by SeizureSaladd** [comment]
It depends on what frame rate you set using the command,

**Comment by wlumee** [comment]
I set it on 1000 so it would be uncapped to the max. ://///

**Comment by SeizureSaladd** [comment]
> I set it on 1000 so it would be uncapped to the max. ://///
> 
> 

That's weird probably because you're in full screen

**Comment by wlumee** [comment]
its still capped.

**Comment by wlumee** [comment]
out of fullscreen

**Comment by wlumee** [comment]
yes
