### ISSUE TITLE
Irreversibly caps FPS at 50 after running once

### ISSUE THREAD

**Issue by slashvalkyrie** [lanylow/rbxfpsunlocker-osx#50]
After a recent Roblox update, I ran the FPS unlocker and my FPS was capped at 50. After quitting and restarting Roblox, the FPS was still capped at 50. In order to return to 60fps, I had to delete and reinstall— and trying again on the newly installed Roblox, the FPS was again irreversibly capped at 50fps.

M1 Mac Mini on macOS 13 Ventura

**Comment by slashvalkyrie** [comment]
Seems to have fixed itself...

**Comment by SeizureSaladd** [comment]
I haven't tested in Ventura yet. I'll go check it out and get back to this.

**Comment by SeizureSaladd** [comment]
Forgot Ventura is still in beta. If after official release this problem persists I'll look into it.
