### ISSUE TITLE
I cannot use my FPS commands because It always says "command not found"

### ISSUE THREAD

**Issue by spicykeyyss** [lanylow/rbxfpsunlocker-osx#51]
<img width="1600" alt="Screenshot 2022-07-15 at 20 22 57" src="https://user-images.githubusercontent.com/109385752/179296770-f8adae83-01d2-47bc-806d-6a50500b9720.png">

**Comment by spicykeyyss** [comment]
I accidentally uninstalled FPS unlocker and when i installed it back my fps command didn't work even though I used it before I uninstalled the FPS unlocker and it worked just fine.

**Comment by slashvalkyrie** [comment]
That means you're using the wrong path. Drag and drop the FPS unlocker file into Terminal and look at the path it shows you. CD over there and then try running ./rbxfpsunlocker again.

**Comment by spicykeyyss** [comment]
@slashvalkyrie wait I don't really understand because I am kinda new to github can u add my discord and help me on there pls i would appreciate it if u can my discord is fwtrevah#0001

**Comment by snoopchallenge** [comment]
alternatively, place it on the desktop where you are running it from or (i use windows so idk if mac has this) right click and copy as path then you can ./ that

**Comment by slashvalkyrie** [comment]
To get the copy as path option, you'll need to option+right click and select "Copy [file] as Pathname", but it does the exact same thing as dragging and dropping into terminal.

**Comment by spicykeyyss** [comment]
@slashvalkyrie I am using the correct path The /Users/xyz../Desktop right?

**Comment by SeizureSaladd** [comment]
you're forgetting to cd into file loaction and it can't find the file
