### ISSUE TITLE
Have you thought of making the FPS unlocker run the background? (Like the Windows on does)

### ISSUE THREAD

**Issue by YousufSSyed** [lanylow/rbxfpsunlocker-osx#53]
As of now, the FPS Unlocker for Windows stays running in the background after opening the icon. When I would join games, the FPS unlocker would automatically unlock the framerate. For this macOS one, it has to be activated for every session with a command.

**Comment by snoopchallenge** [comment]
ngl i would argue that the current method is more simple

**Comment by YousufSSyed** [comment]
But what about when leaving and rejoining games. Sure you could just make a .sh file or whatnot (I actually recently got a PR merged with documentation on it!), but to have it work continuously would be more convenient. The way the Windows app works is that you open it, and stays open in the background with a system tray icon.

What could be done is to either have a GUI app, with options to show it the menu bar and or the GUI app in both. When it's open either way, it can keep running in the background to change the ROBLOX FPS cap.

**Comment by lanylow** [comment]
Yes, I have thought of that but I'm not willing to make any feature updates because I don't even own a mac and asking someone to test my code every other minute is way too inconvenient for me.
