### ISSUE TITLE
not uncapping

### ISSUE THREAD

**Issue by seppata** [lanylow/rbxfpsunlocker-osx#57]
i launch, put my password in and when i click "FPS Cap" and click the one i want it closes unexpectedly and no changes to my fps

**Comment by SeizureSaladd** [comment]
What macOS version are you on?

**Comment by seppata** [comment]
10.15.7

**Comment by SeizureSaladd** [comment]
have you tried just not clicking the fps cap because it automatically sets it to 10000 if roblox appears

**Comment by seppata** [comment]
still capped at 60, unsure if im doing it wrong

**Comment by seppata** [comment]
bit of an update it seems like i have more frames but its still locked at 60

**Comment by SeizureSaladd** [comment]
Did the original unlocker work?

**Comment by Tyetonix** [comment]
Hey SeizureSaladd Can I have the older version of the rbxfpsunlocker since my mac isnt compatible with the latest one?

**Comment by seppata** [comment]
yeah, the older version works and i've been using it since

**Comment by SherpGH** [comment]
> i launch, put my password in and when i click "FPS Cap" and click the one i want it closes unexpectedly and no changes to my fps

yeah it crashes for me aswell when clicking one of the options

**Comment by SeizureSaladd** [comment]
Hmm I'll look into it. In the meantime just use the old FPS unlocker.

**Comment by SherpGH** [comment]
> Hmm I'll look into it. In the meantime just use the old FPS unlocker.

hey so i think i know how to "fix" it, for it to not crash, you'd want the fps unlocker to be open before you open the Roblox game and that seems to unlock the fps without crashing. having the fps unlocker open after crashes it when you press an FPS to cap it to like 75 etc.

**Comment by CyberFlameGO** [comment]
> > Hmm I'll look into it. In the meantime just use the old FPS unlocker.
> 
> hey so i think i know how to "fix" it, for it to not crash, you'd want the fps unlocker to be open before you open the Roblox game and that seems to unlock the fps without crashing. having the fps unlocker open after crashes it when you press an FPS to cap it to like 75 etc.

Can confirm - doesn't really make sense as to why though, seeing as the process checks for instances of RobloxPlayer; I'd assume the problem lays in that realm of the codebase

**Comment by SeizureSaladd** [comment]
> > > Hmm I'll look into it. In the meantime just use the old FPS unlocker.
> 
> > 
> 
> > hey so i think i know how to "fix" it, for it to not crash, you'd want the fps unlocker to be open before you open the Roblox game and that seems to unlock the fps without crashing. having the fps unlocker open after crashes it when you press an FPS to cap it to like 75 etc.
> 
> 
> 
> Can confirm - doesn't really make sense as to why though, seeing as the process checks for instances of RobloxPlayer; I'd assume the problem lays in that realm of the codebase

I am honestly baffled at this point. The new UI uses the EXACT same unlocking code and whatnot from the original and the fact that it doesn't work is weird as hell. I'll be closing this issue if there aren't any more replies in the coming days but if you think you got a fix then make a pull request! This is open source software and anyone is free to contribute!

**Comment by CyberFlameGO** [comment]
> > > > Hmm I'll look into it. In the meantime just use the old FPS unlocker.
> > 
> > 
> > > 
> > 
> > 
> > > hey so i think i know how to "fix" it, for it to not crash, you'd want the fps unlocker to be open before you open the Roblox game and that seems to unlock the fps without crashing. having the fps unlocker open after crashes it when you press an FPS to cap it to like 75 etc.
> > 
> > 
> > Can confirm - doesn't really make sense as to why though, seeing as the process checks for instances of RobloxPlayer; I'd assume the problem lays in that realm of the codebase
> 
> I am honestly baffled at this point. The new UI uses the EXACT same unlocking code and whatnot from the original and the fact that it doesn't work is weird as hell. I'll be closing this issue if there aren't any more replies in the coming days but if you think you got a fix then make a pull request! This is open source software and anyone is free to contribute!

I'll try to take a look, and I believe the problem lays in prematurely exiting the UI (and therefore the process), rather than the actual unlocking code itself

**Comment by SeizureSaladd** [comment]
> > > > > Hmm I'll look into it. In the meantime just use the old FPS unlocker.
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > hey so i think i know how to "fix" it, for it to not crash, you'd want the fps unlocker to be open before you open the Roblox game and that seems to unlock the fps without crashing. having the fps unlocker open after crashes it when you press an FPS to cap it to like 75 etc.
> > > 
> > > 
> > > Can confirm - doesn't really make sense as to why though, seeing as the process checks for instances of RobloxPlayer; I'd assume the problem lays in that realm of the codebase
> > 
> > 
> > I am honestly baffled at this point. The new UI uses the EXACT same unlocking code and whatnot from the original and the fact that it doesn't work is weird as hell. I'll be closing this issue if there aren't any more replies in the coming days but if you think you got a fix then make a pull request! This is open source software and anyone is free to contribute!
> 
> I'll try to take a look, and I believe the problem lays in prematurely exiting the UI (and therefore the process), rather than the actual unlocking code itself

If you can find a fix, please make a pull request. I'll be sure to test it and make a new release.
