### ISSUE TITLE
it goes back to 60 fps

### ISSUE THREAD

**Issue by Rackstar5** [lanylow/rbxfpsunlocker-osx#6]
so when i set the fps like for example 120 its at 120 and then goes back down to 60 when i open the game again can u help with that?

**Comment by jwhazy** [comment]
How difficult would it be to have it wait around in the background and auto inject?

**Comment by lanylow** [comment]
> How difficult would it be to have it wait around in the background and auto inject?

1. Nothing is being injected.
2. Easy, but for now there is no reason to do that since you'd need the console to be opened all the time. It's going to be running in the background like the windows version when the UI is done.
