### ISSUE TITLE
Issues with the app (macos monterey version 12.5.1)

### ISSUE THREAD

**Issue by Hrry0122** [lanylow/rbxfpsunlocker-osx#63]
The unlocker dosent unlock the fps. Ive tried more than 10times and it still dosent work. also whenever i try to cap to any number the application just shuts down.

**Comment by SeizureSaladd** [comment]
What the heck even macOS Monterey ok I'll look in to it. For now just use an older version.

**Comment by Hrry0122** [comment]
ok. Monterey Is the latest software for mac os

**Comment by SeizureSaladd** [comment]
> ok. Monterey Is the latest software for mac os

I meant an older version of the fps unlocker
