### ISSUE TITLE
OSX FPS UNLOCKER CRASHES

### ISSUE THREAD

**Issue by MikeDaMan21** [lanylow/rbxfpsunlocker-osx#64]
Most of the time, I have to continually quit and relaunch. Every time when I click an FPS option then it crashes. After opening it like 8 times then it works

**Comment by SeizureSaladd** [comment]
We know it doesn't work lol we're trying to fix it. In the mean time use an older version of the FPS unlocker.

**Comment by Jannatul89sInGithub** [comment]
Just set your FPS before opening a Roblox game, then it will work
