### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Jannatul89sInGithub** [lanylow/rbxfpsunlocker-osx#67]
Im using macOS Monterey btw. for some reason when i open the roblox fps unlocker and set my fps cap, it crashed. like the menu bar item disappeared so i opened it again, set my fps cap again it crashed again. I was using version 1.2.0

**Comment by SeizureSaladd** [comment]
Hey, would you mind being a test subject for a potential fix? I know this might be a bit random but I'm gonna try and fix the problem when I get back home tomorrow.

**Comment by Jannatul89sInGithub** [comment]
I'll think about it. And also I downloaded the 1.0.1 version yesterday. then the next day i used the 1.2.0 version and suddenly, its working.

**Comment by Josproyeoh** [comment]
Also the UI version is not quite working

**Comment by Mosquitobit** [comment]
@SeizureSaladd      I've also been experiencing crashes when you set a custom fps. Also i found a soultion to the full screen problem refrence https://github.com/lanylow/rbxfpsunlocker-osx/issues/66.

Hope this helps with your fps im still not sure what causes the crashes i'll look into it.

**Comment by Jannatul89sInGithub** [comment]
recording my screen does help, but i found a better solution, i used quartz debug, i turned off vertical sync and it worked. https://youtu.be/WbfJ-cYOxNM

download link: https://mega.nz/file/uU5x1KwI#GmYje_71A-s5mAjuIvlvtd9ITHSnfWP2O98-2x8-pgI
