### ISSUE TITLE
When you put it in full screen it doesnt work when it isnt in full screen it works perfectly fine

### ISSUE THREAD

**Issue by Josproyeoh** [lanylow/rbxfpsunlocker-osx#68]
Here is proof but when you interact with other applications or the mac taskbar it will spike the fps and then drop back to 60 btw i am on macOS big sur
![IMG_5468](https://user-images.githubusercontent.com/112959904/188662582-de14b62c-1382-4c1f-a26b-761ba8c1f003.JPG)
![IMG_5469](https://user-images.githubusercontent.com/112959904/188662719-8bb9f0f1-f3d9-4e69-ba1d-bbc5212c9983.JPG)

**Comment by Mosquitobit** [comment]
@Josproyeoh had a similar issue I found a solution check https://github.com/lanylow/rbxfpsunlocker-osx/issues/66. 

Hope this helps

**Comment by Josproyeoh** [comment]
Ok I just tried using medal and run in the background but the fps just drop to like 30-40 or my mac just simply can handle to much processes running.

**Comment by Jannatul89sInGithub** [comment]
recording your screen does help make it work in full screen, but i found a better solution. Not only does it help make it work in fullscreen but also makes your fps higher than 120 (if your mac is powerful). I used quartz debug, i turned off vertical sync, and it made the fps higher than 120 and also worked in full screen. heres a video if you don't understand https://youtu.be/WbfJ-cYOxNM

heres the download link: https://mega.nz/file/uU5x1KwI#GmYje_71A-s5mAjuIvlvtd9ITHSnfWP2O98-2x8-pgI

**Comment by SeizureSaladd** [comment]
This is an issue with macOS as it attempts to "optimize" the full screen window after macOS version OSX v10.6.
