### ISSUE TITLE
I found a better way to fix the FPS unlocker not working in fullscreen

### ISSUE THREAD

**Issue by Jannatul89sInGithub** [lanylow/rbxfpsunlocker-osx#69]
You have to download Quartz Debug and turn off vertical sync. Not only does it work in fullscreen, your FPS is also higher than 120 (if your device is powerful enough). Heres a video showing you how to do it: https://youtu.be/WbfJ-cYOxNM

and heres the download link: https://mega.nz/file/uU5x1KwI#GmYje_71A-s5mAjuIvlvtd9ITHSnfWP2O98-2x8-pgI

**Comment by SeizureSaladd** [comment]
This violates Apple's debug tools EULA and is illegal ad by downloading them you agree to not distributing the tools. (Very stupid apple thing I know)
