### ISSUE TITLE
failed to get unlocker

### ISSUE THREAD

**Issue by cuhrystul** [lanylow/rbxfpsunlocker-osx#7]
it keeps saying "failed to get rloblox unlocker" in terminal

**Comment by cuhrystul** [comment]
rloblox process info* not unlocker

**Comment by lanylow** [comment]
Are you sure you're running it as root?

**Comment by mist-l** [comment]
Roblox has to be open before you run the command.

**Comment by cuhrystul** [comment]
> Are you sure you're running it as root?

how do u do that

**Comment by lanylow** [comment]
Read the [readme](https://github.com/lanylow/rbxfpsunlocker-osx/blob/main/README.md).

**Comment by cuhrystul** [comment]
> Read the [readme](https://github.com/lanylow/rbxfpsunlocker-osx/blob/main/README.md).

theres nothing in there that tells me how to run it as root

**Comment by lanylow** [comment]
You have exact instructions in there. `sudo` means run as root.

**Comment by cuhrystul** [comment]
> You have exact instructions in there. `sudo` means run as root.

it worked omfg tysm. do i have to type it into terminal every time?

**Comment by lanylow** [comment]
For now yes, a graphical interface is probably going to be added sooner or later.
