### ISSUE TITLE
Fps unlocker isnt working

### ISSUE THREAD

**Issue by retire4562** [lanylow/rbxfpsunlocker-osx#73]
everytime i try to use it by doing the terminal it says comand not found

**Comment by lanylow** [comment]
Which command is not found? Can you post the full output?

**Comment by cadenwsm** [comment]
> Which command is not found? Can you post the full output?

it doesnt say, when we put the command to unblock and after we put our pass in it says command not found

**Comment by lanylow** [comment]
Where did you save the file?

**Comment by cadenwsm** [comment]
> Where did you save the file?

downloads

**Comment by lanylow** [comment]
Assuming you’ve extracted the zip file, try `sudo ~/Downloads/rbxfpsunlocker_osx 0`.

**Comment by cadenwsm** [comment]
> Assuming you’ve extracted the zip file, try `sudo ~/Downloads/rbxfpsunlocker_osx 0`.

it works but how do i get passed the 120 fps cap on monetery, turning off vsync doesnt seem to work

**Comment by cadenwsm** [comment]
> > Assuming you’ve extracted the zip file, try `sudo ~/Downloads/rbxfpsunlocker_osx 0`.
> 
> it works but how do i get passed the 120 fps cap on monetery, turning off vsync doesnt seem to work

unless im doing it wrong

**Comment by lanylow** [comment]
I don’t have this issue so I can only point you to #42. I don’t know any other solutions for that.

**Comment by cadenwsm** [comment]
> I don’t have this issue so I can only point you to #42. I don’t know any other solutions for that.

my vsync doesnt seem to be opening is it because i turned off sip

**Comment by cadenwsm** [comment]
> > I don’t have this issue so I can only point you to #42. I don’t know any other solutions for that.
> 
> my vsync doesnt seem to be opening is it because i turned off sip

nvm i fixed it

**Comment by cadenwsm** [comment]
> I don’t have this issue so I can only point you to #42. I don’t know any other solutions for that.

YOOOOOO VSYNC WORKS IM ON 210 FPS

**Comment by lanylow** [comment]
Glad to hear that, I will close the issue.
