### ISSUE TITLE
This is to do with macOS' new update (Ventura)

### ISSUE THREAD

**Issue by James22rx** [lanylow/rbxfpsunlocker-osx#77]
The FPS Unlocker no longer works on the newest version of macOS (Version 13.0 (Ventura)) It worked for me before I updated my PC and I always use this so I would appreciate this issue to be resolved promptly.

Thank You. James.

**Comment by lanylow** [comment]
Can you specify which version of the unlocker the issue occurs in (console / ui)?

**Comment by James22rx** [comment]
This issue occurs in the console as it says 'FPS Cap set to 120.0' but it doesn't actually uncap my fps and it is stuck at 60. i have tested it on all versions too.

**Comment by James22rx** [comment]
This is an issue with computer version which i think is console

**Comment by James22rx** [comment]
this issue occurs in all of the versions.

**Comment by jwhazy** [comment]
@James22rx Can you please add rbxfpsunlocker to your full disk access apps, restart your Mac fully and try again? 

Tutorial here for more information: https://c-command.com/spamsieve/help/granting-full-disk-acce

**Comment by jwhazy** [comment]
If this works, try the UI version and see if it is fixed on there also. Reply with your results.

**Comment by James22rx** [comment]
[image: Screenshot 2022-10-27 at 10.14.42.png][image: Screenshot 2022-10-27
at 10.14.47.png]
This version does not work either (1.2.0)

**Comment by James22rx** [comment]
[image: Screenshot 2022-10-27 at 10.11.51.png][image: Screenshot 2022-10-27
at 10.12.00.png]
Hi, this is version 1.0.1, still doesn't work.

**Comment by James22rx** [comment]
i have added it to my full disk access and restarted and it still doesnt work
i think that you may need to update the code or add an option :rbxfpsunlocker (Ventura):

**Comment by lanylow** [comment]
Try compiling the code yourself and see if it works.

**Comment by James22rx** [comment]
how do i do that

**Comment by James22rx** [comment]
lanylow could you add me on discord so we can discuss this issue faster? @James22rx#2789

**Comment by landlikescomputers** [comment]
Hi lanylow, I also have problem with this, and I don't konw how to solve it. Please help me with this. Soon the better.

Discord: yes it is land#7235

Have a nice day, I look forward to your response.

**Comment by lanylow** [comment]
Download `rbxfpsunlocker_ventura.zip` from the latest release.
