### ISSUE TITLE
FPS Unlocker does not unlock past 60

### ISSUE THREAD

**Issue by xxDementia** [lanylow/rbxfpsunlocker-osx#80]
MacOS 13 (Ventura)
FPS Unlocker Version v2.0.0
Used Quartz Debug, no effect

**Comment by SeizureSaladd** [comment]
Are you sure you ran it?

**Comment by xxDementia** [comment]
Yes
![image](https://user-images.githubusercontent.com/69117597/198786698-935c41ba-9e51-4707-9e7f-197212e52266.png)

**Comment by lanylow** [comment]
Download `rbxfpsunlocker_ventura.zip` from the latest release.
