### ISSUE TITLE
[MacOS Ventura Beta 13.0] RBX_FPSUNLOCKER NOT WORKING

### ISSUE THREAD

**Issue by landlikescomputers** [lanylow/rbxfpsunlocker-osx#82]
Hello devs if you are reading this. I am here writing this issue to **inform and question** you why roblox fps unlocker (mac) does not work. I know that it is probably because of Ventura, but I want to know how to solve it. Please respond to this, I am looking forward, soon the better. (I use 1.2.0 I think?)

**Comment by lanylow** [comment]
Download `rbxfpsunlocker_ventura.zip` from the latest release.
