### ISSUE TITLE
macOS FPS Unlocker v2.0.0 - FPS cap doesn't go above 60 (not my PC not being able to handle it) but caps under 60 (22, 45, 15, 38 etc)

### ISSUE THREAD

**Issue by cull0** [lanylow/rbxfpsunlocker-osx#85]
Using [ https://github.com/lanylow/rbxfpsunlocker-osx/releases/tag/v2.0.0 ], I followed all the steps correctly and I am able to cap the FPS to things under 60, for example I can make the cap 25, 56, 12 or whatever, but when I set the cap to over 60, for example 120, 233, 555 or whatever, it just stays at 60. I have used an fps unlocker on mac before this and as soon as I updated to macOS Ventura my fps unlocker didn't work so I tried to use v2.0.0 but it doesn't go over 60. I need some help and I don't know what to do.

**Comment by lanylow** [comment]
Are you sure you downloaded `rbxfpsunlocker_ventura.zip` and not the monterey version?

**Comment by cull0** [comment]
> Are you sure you downloaded `rbxfpsunlocker_ventura.zip` and not the monterey version?

Yes, positive.

**Comment by lanylow** [comment]
What refresh rate is your monitor set to? If you can't find it anywhere try looking in specifications of your mac.

**Comment by cull0** [comment]
> What refresh rate is your monitor set to? If you can't find it anywhere try looking in specifications of your mac.

It is 60hz, but I used another FPS unlocker made by you and Seizure and it worked and I did see very noticeable differences and when I viewed my FPS in-game it was 120 FPS. Although the monitor is 60hz I assure you there was a noticeable difference. What I can't manage to do is get the FPS to actually change above 60 FPS in game.

**Comment by cull0** [comment]
![Uploading Screenshot 2022-10-30 at 00.23.59.png…]()

**Comment by lanylow** [comment]
I know there is a noticeable difference, but that's not the point. My monitor is 144Hz and my frame rate doesn't go above that, so I guess ventura is locking it to monitor's refresh rate, similarly as older versions locked it to 120 (at least that's what many issues said). Using tools such as Quartz Debug didn't work for me, and there isn't any other known solution to this.

**Comment by cull0** [comment]
> I know there is a noticeable difference, but that's not the point. My monitor is 144Hz and my frame rate doesn't go above that, so I guess ventura is locking it to monitor's refresh rate, similarly as older versions locked it to 120 (at least that's what many issues said). Using tools such as Quartz Debug didn't work for me, and there isn't any other known solution to this.

So even though the one I used before worked with 60 Hz and went to 120 FPS there is no solution for Ventura?

**Comment by lanylow** [comment]
You reached 120 FPS in macOS monterey, do I understand correctly?

**Comment by cull0** [comment]
> You reached 120 FPS in macOS monterey, do I understand correctly?

Yes.

**Comment by lanylow** [comment]
So as I said, this must be a "problem" with macOS ventura. The unlocker isn't faulty for this behavior.

**Comment by cull0** [comment]
> So as I said, this must be a "problem" with macOS ventura. The unlocker isn't faulty for this behavior.

So the version you released isn't functionable?

**Comment by cull0** [comment]
Is there a way to change the refresh rate (with another monitor) or to go back to macOS monterey?

**Comment by lanylow** [comment]
I think if you had another monitor with higher refresh rate it would work. You should be able to downgrade to monterey using the recovery mode, but this goes beyond the scope of this issue.

**Comment by cull0** [comment]
Would this certainly fix the issue or not?

**Comment by lanylow** [comment]
My main monitor is set to 144 Hz and the secondary is set to 60 Hz, I am getting 144 FPS in Roblox after using this tool. All I can say is that it works for me.

**Comment by cull0** [comment]
> My main monitor is set to 144 Hz and the secondary is set to 60 Hz, I am getting 144 FPS in Roblox after using this tool. All I can say is that it works for me, but I do not guarantee anything.

Are you using Ventura and the new FPS unlocker code?

**Comment by lanylow** [comment]
Yes.

**Comment by cull0** [comment]
> Yes.

Do you game on roblox and is there any input delay on the second monitor? And is it easy to set up the second monitor if I try to connect it to my iMac?

**Comment by lanylow** [comment]
I am playing on the higher refresh rate monitor. Once you plug it in, it should automatically display your second screen, then you have to go into settings and set the refresh rate of it to one supported by the monitor. I have the 144 Hz monitor set as my main display, I don't know if that matters.

**Comment by cull0** [comment]
> I am playing on the higher refresh rate monitor. Once you plug it in, it should automatically display your second screen, then you have to go into settings and set the refresh rate of it to one supported by the monitor. I have the 144 Hz monitor set as my main display, I don't know if that matters.

Thanks so much for helping

**Comment by landlikescomputers** [comment]
lanylow, if my macbook's hz is just 60 and I don't have any secondary moniter, does it mean I can't cap my fps above 60?

**Comment by lanylow** [comment]
If you are on ventura - yes, if you're using an older version you can go up to 120 Hz without disabling vsync.

**Comment by landlikescomputers** [comment]
what older version???

**Comment by lanylow** [comment]
No, I meant older macOS version such as monterey.

**Comment by landlikescomputers** [comment]
welp.. i can't convert ventura back to monterey :(

**Comment by landlikescomputers** [comment]
will ventura have this issue fixed ever? like yeah..

**Comment by lanylow** [comment]
This is not an issue, that's just how ventura works and right now you can't do anything about it. Maybe someone will find a way of unlocking ventura's built-in limit.

**Comment by landlikescomputers** [comment]
ty..

**Comment by landlikescomputers** [comment]
last question, do you think ventura will like add smth like that in the future?

**Comment by lanylow** [comment]
What exactly do you mean by "something like that"?

**Comment by landlikescomputers** [comment]
like going up to 120 hz

**Comment by James22rx** [comment]
my mac is 144hertz but while using the fps unlocker i only hit 60, it lets me go lower but no higher than 60, is there any way to fix this issue?

**Comment by lanylow** [comment]
Make sure it's set to 144 Hz in display settings.

**Comment by QQuarterQQ** [comment]
I get an error like command not found

**Comment by James22rx** [comment]
you can no longer change your hertz level on ventura so idk how to fix this

**Comment by lanylow** [comment]
You can set your refresh rate in Settings > Displays > Refresh rate. If nothing above 60 Hz is available it means your monitor doesn't support it.

**Comment by lanylow** [comment]
I'm closing this issue because it has been explained and it now becomes a support chat.
