### ISSUE TITLE
rbxfpsunlocker-osx macOS Ventura

### ISSUE THREAD

**Issue by cull0** [lanylow/rbxfpsunlocker-osx#88]
(to lany, hz issue is irrelevant today and you might remember me from yesterday)

When I try to cap my FPS at all, it says there is no command found, I don't know why or what's wrong but I am 100% sure I downloaded the right files..

<img width="439" alt="Screenshot 2022-10-30 at 19 54 29" src="https://user-images.githubusercontent.com/116982989/198898995-58d22b48-d89e-46db-96dc-a0e446eee2ea.png">

**Comment by cull0** [comment]
sudo ./rbxfpsunlocker_osx < cap > doesn't seem to be a command according to my terminal

**Comment by lanylow** [comment]
By the first command I assume you have the file in your Downloads folder. The dot in the command refers to the folder you're currently in and that is your Home folder. In this scenario you can try doing `sudo ./Downloads/rbxfpsunlocker_osx`.

**Comment by cull0** [comment]
Thanks mate
