### ISSUE TITLE
Windows 10 - Roblox for Windows (from MS Store) not working

### ISSUE THREAD

**Issue by ItsGamingTube** [lanylow/rbxfpsunlocker-osx#9]
![image](https://user-images.githubusercontent.com/66141420/152341733-c3e233d4-19ac-4c8d-b2bc-695138c79706.png)
I get that error when trying to use FPS Unlocker with the Windows app. I use multi-clients in Jailbreak so i have to use the Roblox for Windows 10 app to start multiple instances.

**Comment by lanylow** [comment]
You have to compile the source code yourself, support for windows store is in the repo already, just not released.

**Comment by RyanScripz** [comment]
I Think its because the program cant find a task sceduler variablle
