### ISSUE TITLE
how can I check my fps on roblox on mac

### ISSUE THREAD

**Issue by fregtjgg** [lanylow/rbxfpsunlocker-osx#92]

**Comment by lanylow** [comment]
Click `Shift + F5`.

**Comment by fregtjgg** [comment]
> Click `Shift + F5`.

what does disabling vsync do

**Comment by lanylow** [comment]
V-Sync is basically synchronizing your frames with your monitor's refresh cycles. This means your FPS can't go above your monitor's refresh rate.

**Comment by fregtjgg** [comment]
i just disabled it with quartz also shift f5 isn't doing anything for me on roblox

**Comment by fregtjgg** [comment]
i got it i had to do cmd shift f5

**Comment by fregtjgg** [comment]
> V-Sync is basically synchronizing your frames with your monitor's refresh cycles. This means your FPS can't go above your monitor's refresh rate.

my fps is stuck at 60

**Comment by lanylow** [comment]
Quartz Debug's disable v-sync feature doesn't work on ventura.

**Comment by fregtjgg** [comment]
> Quartz Debug's disable v-sync feature doesn't work on ventura.

im on Monterey

**Comment by lanylow** [comment]
Did you run the unlocker?

**Comment by fregtjgg** [comment]
> Did you run the unlocker?

yes i think its just my mac because when i make the window smaller it goes up

**Comment by lanylow** [comment]
Oh well, you can't get high frame rates if your mac won't handle it.

**Comment by fregtjgg** [comment]
> Oh well, you can't get high frame rates if your mac won't handle it.

yeah i have a 2015 mac the newer ones run high fps?

**Comment by fregtjgg** [comment]
early 2015
