### ISSUE TITLE
Failed to get Roblox process info

### ISSUE THREAD

**Issue by gunnajsu** [lanylow/rbxfpsunlocker-osx#93]
![Screenshot 2022-11-02 at 6 10 58 PM](https://user-images.githubusercontent.com/115434137/199630358-aa894518-3c4c-4f14-9f0a-2e74e704dfbe.png)

**Comment by gunnajsu** [comment]
I also had Roblox open btw

**Comment by gunnajsu** [comment]
someone told me that it was cuz of a new rblx update

**Comment by dtbMilan** [comment]
bru same , it was working and then outta nowhere it stopped.

**Comment by probabalyJackie** [comment]
same here

**Comment by TheCodingPsn** [comment]
same

**Comment by probabalyJackie** [comment]
prolly bc of the roblox update or anticheat that disables injecting script thingys

**Comment by grrrrrrbear** [comment]
same

**Comment by jan-vlcek** [comment]
So how do I fix it? (I have the same problem.)

**Comment by grrrrrrbear** [comment]
i need to know too its so annoying randomly not working

**Comment by grrrrrrbear** [comment]
Someone know what region he is?

**Comment by lanylow** [comment]
Refer to #96.

**Comment by grrrrrrbear** [comment]
does this all have to do with roblox update or mac?

**Comment by grrrrrrbear** [comment]
![Skärmavbild 2022-11-04 kl  10 09 16](https://user-images.githubusercontent.com/87470326/199935393-bde880a6-e3c0-4029-8d27-b3f5933bd991.png)

doesnt work when im in a game

**Comment by lanylow** [comment]
Please refer to instructions from the latest release.
