### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by capincodi6** [lanylow/rbxfpsunlocker-osx#94]
I did all the steps right and it still didn't work it said to me "command not found" ???
<img width="528" alt="Screen Shot 2022-11-03 at 5 06 01 PM" src="https://user-images.githubusercontent.com/56496234/199645657-6f5cb36f-f7b4-41a9-8968-bc3a4610f9e5.png">

**Comment by lanylow** [comment]
Remove the dot after sudo.
