### ISSUE TITLE
FpsUnlocker says "Exception: Roblox is not running"

### ISSUE THREAD

**Issue by TheCodingPsn** [lanylow/rbxfpsunlocker-osx#95]
<img width="563" alt="Screen Shot 2022-11-03 at 4 28 57 pm" src="https://user-images.githubusercontent.com/78592389/199653306-c1527d68-1a84-4c95-9bd8-975742fc47a4.png">

Even though my Roblox is open, the fps unlocker doesn't work. This may be because of the new update, which may have changed the Roblox directory in macOS. If you're wondering I'm on a MacBook air (M1, 2020).

**Comment by dtbMilan** [comment]
my roblox would be open and running but it would say error bc its somehow not detecting it

**Comment by lanylow** [comment]
The `-s` tag is used to unlock Roblox Studio. I assume you want to use it on the player, so you need to run it without `-s`.
