### ISSUE TITLE
FPS unlocker saying exception: base_process constructor failed

### ISSUE THREAD

**Issue by rexulot** [lanylow/rbxfpsunlocker-osx#96]
The unlocker's been working perfectly but I haven't used it for like a week and tried to boot it up today and it gave this error message. i do not know how to fix it or what I've done to make brokey if anyone could help, it would be greatly appreciated
<img width="570" alt="Screen Shot 2022-11-03 at 5 59 55 pm" src="https://user-images.githubusercontent.com/117344994/199672452-fe24db5d-826e-4c41-842f-ea41f7341afb.png">

**Comment by dtbMilan** [comment]
yep exactly the same for me.

**Comment by Agony0909** [comment]
same

**Comment by grrrrrrbear** [comment]
same for me too worked fine then randomly stopped working

**Comment by cull0** [comment]
Same

**Comment by lanylow** [comment]
This is indeed caused by a Roblox update. I will see what I can do, but to me it looks like a security enhancement from their side.

**Comment by grrrrrrbear** [comment]
> 

which means you might not be able to remake it or could you specify a little bit

**Comment by grrrrrrbear** [comment]
so we all got the same problem?
is it fixable?

**Comment by OrateMA** [comment]
@lanylow do you when it prob gonna be done?

**Comment by jan-vlcek** [comment]
> This is indeed caused by a Roblox update. I will see what I can do, but to me it looks like a security enhancement from their side.

So when do you think you will fix it?

**Comment by grrrrrrbear** [comment]
> > This is indeed caused by a Roblox update. I will see what I can do, but to me it looks like a security enhancement from their side.
> 
> So when do you think you will fix it?

I think hes still in school so we fight have to wait a bit

**Comment by James22rx** [comment]
i get this issue too, roblox has enhanced their security system.

**Comment by foxt** [comment]
```
/usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/RobloxPlayer
/usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/Roblox.app/Contents/MacOS/Roblox
```
ez

**Comment by colwe** [comment]
> 

Does this work?

**Comment by landlikescomputers** [comment]
what does this do??

**Comment by TheCodingPsn** [comment]
@foxt thank you so much for the code, now the fps unlocker works! Maybe lanylow can implement the code before the unlocker runs?

**Comment by probabalyJackie** [comment]
> ```
> /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/RobloxPlayer
> /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/Roblox.app/Contents/MacOS/Roblox
> ```
> 
> ez

damn it works thanks man

**Comment by cull0** [comment]
> > ```
> > /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/RobloxPlayer
> > /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/Roblox.app/Contents/MacOS/Roblox
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ez
> 
> damn it works thanks man

How do you use this?

**Comment by TheCodingPsn** [comment]
> 

just copy and paste the first line and second line into terminal

**Comment by spiriteds** [comment]
how can we apply this in the 1.20 version, with the user interface?

**Comment by foxt** [comment]
> what does this do??

removed the signature which includes a tag which tells macos to not allow anyone to modify this process

**Comment by grrrrrrbear** [comment]
it says it works for me but still it doesnt unlock the fps

**Comment by grrrrrrbear** [comment]
![Skärmavbild 2022-11-05 kl  11 31 43](https://user-images.githubusercontent.com/87470326/200115497-e19199a4-1f0b-4a8e-a62d-03a39a5c0874.png)

**Comment by lanylow** [comment]
> ```
> /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/RobloxPlayer
> /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/Roblox.app/Contents/MacOS/Roblox
> ```
> 
> 
>      
>   
> 
> ez

Thanks for finding a workaround. I added a command line option in the latest release that automatically runs these commands.

**Comment by OrateMA** [comment]
Just copy the thing to terminal, then enter, then use the orginal steps like you did before (cd downloads and etc)

**Comment by probabalyJackie** [comment]
> > > ```
> > > /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/RobloxPlayer
> > > /usr/bin/codesign --remove-signature /Applications/Roblox.app/Contents/MacOS/Roblox.app/Contents/MacOS/Roblox
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ez
> > 
> > 
> > damn it works thanks man
> 
> How do you use this?

you copy that into terminal. make sure that you have allowed terminal to edit apps in security and privacy tab in settings

**Comment by probabalyJackie** [comment]
> it says it works for me but still it doesnt unlock the fps

if your screen is 60 htz, it caps it there. use quartz debug to disable v sync
