### ISSUE TITLE
Error when launching version 1.20

### ISSUE THREAD

**Issue by spiriteds** [lanylow/rbxfpsunlocker-osx#97]
When I launched Roblox today this message popped up and I cannot find any way to fix this, I am running the Ventura MacOS, not sure if this could be the reason since I updated a few days ago already. The fpsunlocker was working fine until today, I'm not sure if it has something to do with Roblox's updates but please let me know if there is any way I can fix this, or if I simply cannot use the fpsunlocker anymore. Not sure if this issue is only happening on the 1.20 version or if it affects other versions as well, (I have resorted to using the 1.20 version as the 2.0.0 version is a bit complex to use and I receive far too many error messages such as "command not found" and the 1.20 version has a more user friendly interface.)

Many thanks,
Spirit

Screenshot for reference:
![Screenshot 2022-11-03 at 6 30 48 PM](https://user-images.githubusercontent.com/117354807/199698723-0053d5db-b5ba-47bc-8043-4403da2b1699.png)

**Comment by lanylow** [comment]
Refer to #96.

**Comment by lanylow** [comment]
Please refer to instructions from the latest release.
