### ISSUE TITLE
Logic error: Failed to get roblox process info. UI 1.0.1 MacOS Catalina 10.15.7

### ISSUE THREAD

**Issue by seppata** [lanylow/rbxfpsunlocker-osx#99]
I get an error when i try to uncap, Even when i have roblox open i've tried uninstalling the program restarting my computer. Im not sure whats wrong

**Comment by seppata** [comment]
my bad, i meant to put command sorry

> I get an error when i try to uncap, Even when i have roblox open i've tried uninstalling the program restarting my computer. Im not sure whats wrong

**Comment by SeizureSaladd** [comment]
Known issue; probably caused by new Roblox security. Please wait for a fix.

**Comment by SeizureSaladd** [comment]
Known issue; probably because of Roblox security. We're currently trying to fix.
